CREATE TABLE IF NOT EXISTS bans (
    id        TEXT PRIMARY KEY,
    ip        TEXT NOT NULL,
    reason    TEXT,
    banned_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_bans_ip ON bans(ip);
