CREATE TABLE IF NOT EXISTS telegram_bots (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    token TEXT NOT NULL,
    chat_id TEXT NOT NULL,
    tier TEXT DEFAULT 'basic',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bot_filters (
    id TEXT PRIMARY KEY,
    bot_id TEXT NOT NULL,
    filter_type TEXT NOT NULL,
    filter_value TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
