// Auto-generated by make_polymorphic.py
// Do not edit manually

#ifndef MIRAGE_HASHES_H
#define MIRAGE_HASHES_H

#include <stdint.h>

// Module hashes (28 iters, case-insensitive)
#define HASH_NTDLL_DLL  0x7077A204u
#define HASH_WIN32U_DLL  0xCBE29452u

// Function hashes (27 iters, exact case)
#define HASH_LdrGetProcedureAddress  0x384AF68Du  // LdrGetProcedureAddress
#define HASH_AllocateVirtualMemory  0x6E9471DDu  // NtAllocateVirtualMemory
#define HASH_ProtectVirtualMemory  0xF10879C4u  // NtProtectVirtualMemory
#define HASH_FreeVirtualMemory  0x8897487Fu  // NtFreeVirtualMemory
#define HASH_WriteVirtualMemory  0x69BF2052u  // NtWriteVirtualMemory
#define HASH_ReadVirtualMemory  0x794DAEE4u  // NtReadVirtualMemory
#define HASH_Close  0xFDFC0FB5u  // NtClose
#define HASH_QuerySystemInformation  0x434BF997u  // NtQuerySystemInformation
#define HASH_QueryInformationProcess  0x12CC667Fu  // NtQueryInformationProcess
#define HASH_DelayExecution  0x3A4D6B76u  // NtDelayExecution
#define HASH_OpenFile  0x9FDA0135u  // NtOpenFile
#define HASH_WriteFile  0xDAABADD9u  // NtWriteFile
#define HASH_SetInformationProcess  0x22744339u  // NtSetInformationProcess
#define HASH_OpenKey  0x73AFF332u  // NtOpenKey
#define HASH_QueryValueKey  0xA5B604EBu  // NtQueryValueKey
#define HASH_OpenProcess  0x7F42B2E0u  // NtOpenProcess
#define HASH_CreateThreadEx  0x5D1F58A6u  // NtCreateThreadEx
#define HASH_FlushInstructionCache  0x20574F93u  // NtFlushInstructionCache
#define HASH_CreateEvent  0xBE006931u  // NtCreateEvent
#define HASH_DeleteFile  0x1E74A9BBu  // NtDeleteFile
#define HASH_SetInformationFile  0x4D2A2C80u  // NtSetInformationFile
#define HASH_CreateFile  0xB62F9B6Bu  // NtCreateFile

#endif
