#!/usr/bin/env python3
"""
compute_hashes.py - Pre-compute encrypted hash values for Mirage-C
Mirrors the Zig comptime hash functions for use in C headers/strings.

Algorithm: Rotl-XOR-Mul hash
  Seed:  0x61472f96
  Mul:   0x1B873593
  Add:   0x85EBCA6B

Module hashes: 28 iterations, case-insensitive, XOR before hash
Function hashes: 27 iterations, exact case, XOR before hash
"""

import sys

SEED = 0x61472f96
STRING_KEY_ENC = bytes([0xbf, 0xcd, 0x2f, 0x77,
                         0xdf, 0xd9, 0xb9, 0xf9,
                         0x58, 0xf7, 0x0b, 0xa4,
                         0x49, 0xab, 0xad, 0x3b])

def rotl32(val, n):
    return ((val << n) | (val >> (32 - n))) & 0xFFFFFFFF

def hash_bytes(data, iterations):
    h = SEED
    for b in data:
        for _ in range(iterations):
            h = rotl32(h, 5)
            h = (h ^ b) & 0xFFFFFFFF
            h = (h * 0x1B873593 + 0x85EBCA6B) & 0xFFFFFFFF
    return h

def hash_string(s, iterations, case_insensitive=False):
    data = bytearray()
    for ch in s:
        b = ord(ch)
        if case_insensitive and 0x41 <= b <= 0x5A:
            b += 32
        data.append(b)
    return hash_bytes(data, iterations)

def encrypted_hash_module(s):
    enc = bytes([b ^ STRING_KEY_ENC[i % 16] for i, b in enumerate(s.encode())])
    return hash_bytes(enc, 28)

def encrypted_hash_func(s):
    enc = bytes([b ^ STRING_KEY_ENC[i % 16] for i, b in enumerate(s.encode())])
    return hash_bytes(enc, 27)

def main():
    modules = ["ntdll.dll", "win32u.dll"]
    functions = [
        "LdrGetProcedureAddress",
        "NtAllocateVirtualMemory", "NtProtectVirtualMemory",
        "NtFreeVirtualMemory", "NtWriteVirtualMemory",
        "NtClose", "NtOpenFile", "NtReadVirtualMemory",
        "NtCreateSection", "NtMapViewOfSection",
        "NtQueryInformationProcess", "NtCreateFile",
        "NtWriteFile", "NtQuerySystemInformation",
        "NtDelayExecution", "NtCreateEvent",
        "NtWaitForSingleObject", "NtOpenKey",
        "NtQueryValueKey", "NtSetInformationProcess",
        "NtSetInformationFile", "NtGetContextThread",
        "NtSetContextThread", "NtOpenSection",
        "NtUnmapViewOfSection", "NtCreateThreadEx",
        "NtOpenProcess", "NtResumeThread",
        "NtSuspendThread", "NtDeleteFile",
        "NtFlushInstructionCache", "NtUserGetSystemMetrics",
    ]

    print("// Auto-generated by compute_hashes.py")
    print("// Do not edit manually")
    print()
    print("#ifndef MIRAGE_HASHES_H")
    print("#define MIRAGE_HASHES_H")
    print()
    print("#include <stdint.h>")
    print()
    print("// Module hashes (encryptedHashModule, 28 iters, case-insensitive)")
    for m in modules:
        h = encrypted_hash_module(m)
        define_name = m.upper().replace(".", "_")
        print(f"#define HASH_{define_name}  0x{h:08X}u")
    print()
    print("// Function hashes (encryptedHashFunc, 27 iters, exact case)")
    for f in functions:
        h = encrypted_hash_func(f)
        define_name = f.replace("Nt", "")
        print(f"#define HASH_{define_name}  0x{h:08X}u  // {f}")
    print()
    print("#endif")
    print()

if __name__ == "__main__":
    main()
