#!/usr/bin/env python3
"""
make_polymorphic.py — Regenerate per-build crypto constants.

Each invocation produces a UNIQUE build:
  - random MIRAGE_SEED          (hash seed)
  - random MIRAGE_STRING_KEY_ENC (16-byte XOR string key)
  - regenerates engine.c XOR-obfuscated export arrays
  - regenerates hashes.h        (kept consistent, used as reference)

Usage: python3 tools/make_polymorphic.py
"""
import os
import random
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_H = os.path.join(ROOT, "include", "config.h")
ENGINE_C = os.path.join(ROOT, "src", "syscalls", "engine.c")
HASHES_H = os.path.join(ROOT, "include", "hashes.h")

# Export names that get XOR-obfuscated in engine.c (fallback path)
EXPORTS = [
    "NtAllocateVirtualMemory", "NtProtectVirtualMemory", "NtFreeVirtualMemory",
    "NtWriteVirtualMemory", "NtReadVirtualMemory", "NtClose",
    "NtQuerySystemInformation", "NtQueryInformationProcess", "NtDelayExecution",
    "NtOpenFile", "NtWriteFile", "NtSetInformationProcess", "NtOpenKey",
    "NtQueryValueKey", "NtOpenProcess", "NtCreateThreadEx",
    "NtFlushInstructionCache", "NtCreateEvent", "NtDeleteFile",
    "NtSetInformationFile", "NtCreateFile", "NtEnumerateKey",
]
MODULES = ["ntdll.dll", "win32u.dll"]

# Keep the export-name list above in sync with the one in engine.c.
# The obfuscated array name is derived: "NtFoo" -> _NtFoo_obf


def rotl32(v, n):
    return ((v << n) | (v >> (32 - n))) & 0xFFFFFFFF


def gen_seed():
    while True:
        s = random.getrandbits(32)
        if s != 0:
            return s


def gen_key():
    return bytes(random.getrandbits(8) for _ in range(16))


def c_hex_array(data):
    return ", ".join(f"0x{b:02x}" for b in data)


def xor_string(s, key):
    return bytes(ord(s[i]) ^ key[i % 16] for i in range(len(s)))


def hash_bytes(data, seed, iterations):
    h = seed
    for b in data:
        for _ in range(iterations):
            h = rotl32(h, 5)
            h = (h ^ b) & 0xFFFFFFFF
            h = (h * 0x1B873593 + 0x85EBCA6B) & 0xFFFFFFFF
    return h


def hash_module(s, seed, key):
    enc = bytes(ord(s[i]) ^ key[i % 16] for i in range(len(s)))
    # case-insensitive fold
    data = bytearray()
    for b in enc:
        if 0x41 <= b <= 0x5A:
            b += 32
        data.append(b)
    return hash_bytes(data, seed, 28)


def hash_func(s, seed, key):
    enc = bytes(ord(s[i]) ^ key[i % 16] for i in range(len(s)))
    return hash_bytes(enc, seed, 27)


def rewrite_config(seed, key):
    with open(CONFIG_H, "r", encoding="utf-8") as f:
        text = f.read()

    # MIRAGE_SEED
    text = re.sub(
        r"#define MIRAGE_SEED\s+0x[0-9a-fA-F]+",
        f"#define MIRAGE_SEED            0x{seed:08X}",
        text,
        count=1,
    )

    # MIRAGE_STRING_KEY_ENC block (two comment lines + closing)
    key_line = "    " + ", ".join(f"0x{b:02x}" for b in key) + "   /* polymorphic */"
    pattern = re.compile(
        r"static const unsigned char MIRAGE_STRING_KEY_ENC\[16\] = \{[^}]*\}[,;]?\s*"
    )
    new_block = (
        "static const unsigned char MIRAGE_STRING_KEY_ENC[16] = {\n"
        f"{key_line}\n"
        "};\n"
    )
    text, n = pattern.subn(new_block, text, count=1)
    if n != 1:
        raise SystemExit("[!] config.h: MIRAGE_STRING_KEY_ENC block not found")

    with open(CONFIG_H, "w", encoding="utf-8") as f:
        f.write(text)


def rewrite_engine(seed, key):
    with open(ENGINE_C, "r", encoding="utf-8") as f:
        text = f.read()

    start_marker = "/* ═══════ XOR-obfuscated export names ══════════════════════════ */"
    end_marker = "static void deobf_str"
    start = text.index(start_marker)
    end = text.index(end_marker)
    if start < 0 or end < 0:
        raise SystemExit("[!] engine.c: obfuscated block markers not found")

    lines = [start_marker, ""]
    for name in EXPORTS:
        obf = xor_string(name, key)
        var = name.replace(".", "_")
        lines.append(
            f"static const unsigned char _{var}_obf[{len(obf)}] = "
            f"{{ {c_hex_array(obf)} }};"
        )
    obf = xor_string("ntdll.dll", key)
    lines.append(
        f"static const unsigned char _ntdll_dll_obf[{len(obf)}] = "
        f"{{ {c_hex_array(obf)} }};"
    )
    lines.append("")

    new_block = "\n".join(lines)
    text = text[:start] + new_block + text[end:]

    with open(ENGINE_C, "w", encoding="utf-8") as f:
        f.write(text)


def rewrite_hashes(seed, key):
    out = []
    out.append("// Auto-generated by make_polymorphic.py")
    out.append("// Do not edit manually")
    out.append("")
    out.append("#ifndef MIRAGE_HASHES_H")
    out.append("#define MIRAGE_HASHES_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("// Module hashes (28 iters, case-insensitive)")
    for m in MODULES:
        h = hash_module(m, seed, key)
        dn = m.upper().replace(".", "_")
        out.append(f"#define HASH_{dn}  0x{h:08X}u")
    out.append("")
    out.append("// Function hashes (27 iters, exact case)")
    for f in ["LdrGetProcedureAddress"] + EXPORTS:
        h = hash_func(f, seed, key)
        dn = f.replace("Nt", "").replace(".", "_")
        out.append(f"#define HASH_{dn}  0x{h:08X}u  // {f}")
    out.append("")
    out.append("#endif")
    out.append("")

    with open(HASHES_H, "w", encoding="utf-8") as f:
        f.write("\n".join(out))


def main():
    seed = gen_seed()
    key = gen_key()
    rewrite_config(seed, key)
    rewrite_engine(seed, key)
    rewrite_hashes(seed, key)
    print(f"[+] MIRAGE_SEED = 0x{seed:08X}")
    print("[+] MIRAGE_STRING_KEY_ENC = " + " ".join(f"{b:02X}" for b in key))
    print("[+] engine.c XOR arrays regenerated")
    print("[+] hashes.h regenerated")


if __name__ == "__main__":
    main()
